package GUI;

import java.awt.BorderLayout;
import java.awt.Dimension;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author LeAnhQuan
 */
public class BaoCaoThongKe_GUI extends javax.swing.JFrame {

    
    /**
     * Creates new form BaoCaoThongKe_GUI
     */
    public BaoCaoThongKe_GUI() {
        initComponents();
        showPieChartMonAn();
        showPieChartKhachHang();
        showBarChartDoanhThu();
    }

    public void showPieChartMonAn(){
        DefaultPieDataset pieDataset;
        JFreeChart pieChart;
        PiePlot piePlot;
        ChartPanel chartPanel;
        
        pieDataset = new DefaultPieDataset();
        pieDataset.setValue("Burgers", 9.2);
        pieDataset.setValue("Sandwich", 9.0);
        pieDataset.setValue("Gà rán", 9.2);
        pieDataset.setValue("Tráng miệng", 9.2);
        
        pieChart = ChartFactory.createPieChart3D("Top  4 món ăn yêu thích nhất", pieDataset, true, true, false);
        
        piePlot = (PiePlot) pieChart.getPlot();
        chartPanel = new ChartPanel(pieChart);
        
        pnlPieChartMonAn.add(chartPanel, BorderLayout.CENTER);
        
        pnlPieChartMonAn.setPreferredSize(new Dimension(400, 300));        
        pnlPieChartMonAn.setMinimumSize(new Dimension(400, 300));
        chartPanel.validate();
    }
    
    public void showPieChartKhachHang(){
        DefaultPieDataset pieDataset;
        JFreeChart pieChart;
        PiePlot piePlot;
        ChartPanel chartPanel;
        
        pieDataset = new DefaultPieDataset();
        pieDataset.setValue("Lê Anh Quân", 12);
        pieDataset.setValue("Phan Hoàng Nhật Tân", 9.0);
        pieDataset.setValue("Huỳnh Tuấn Thanh", 5);
        pieDataset.setValue("Đinh Nhật Tân", 3);
        
        pieChart = ChartFactory.createPieChart3D("Top  4 khách hàng chi tiêu nhiều nhất", pieDataset, true, true, false);
        
        piePlot = (PiePlot) pieChart.getPlot();
        chartPanel = new ChartPanel(pieChart);
        
        pnlPieChartKhachHang.add(chartPanel, BorderLayout.CENTER);
        
        pnlPieChartKhachHang.setPreferredSize(new Dimension(400, 300));        
        pnlPieChartKhachHang.setMinimumSize(new Dimension(400, 300));
        chartPanel.validate();
    }
    
    private void showBarChartDoanhThu(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        JFreeChart chart;
        CategoryPlot categoryPlot;
        ChartPanel chartPanel;
        
        dataset.addValue(10000,"Tháng", "T1");        
        dataset.addValue(20000,"Tháng", "T2");
        dataset.addValue(25000,"Tháng", "T3");
        dataset.addValue(12000,"Tháng", "T4");
        dataset.addValue(9000,"Tháng", "T5");
        dataset.addValue(50000,"Tháng", "T6");
        dataset.addValue(10000,"Tháng", "T7");
        dataset.addValue(20000,"Tháng", "T8");
        dataset.addValue(90000,"Tháng", "T9");
        dataset.addValue(5000,"Tháng", "T10");
        dataset.addValue(12000,"Tháng", "T11");
        dataset.addValue(14000,"Tháng", "T12");

        chart = ChartFactory.createBarChart("Doanh thu theo tháng", "Tháng", "1000 VNĐ", 
                dataset, PlotOrientation.VERTICAL, true, true, false);
        
        categoryPlot = chart.getCategoryPlot();
        chartPanel = new ChartPanel(chart);
        
        pnlBarChartDoanhThu.setPreferredSize(new Dimension(1000, 300));        
        pnlBarChartDoanhThu.setMinimumSize(new Dimension(1000, 300));      
        pnlBarChartDoanhThu.setMaximumSize(new Dimension(1000, 300));
        
        pnlBarChartDoanhThu.add(chartPanel, BorderLayout.CENTER);
        pnlBarChartDoanhThu.validate();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPieChartMonAn = new javax.swing.JPanel();
        pnlPieChartKhachHang = new javax.swing.JPanel();
        pnlBarChartDoanhThu = new javax.swing.JPanel();
        pieChartPanel3 = new javax.swing.JPanel();
        pieChartPanel4 = new javax.swing.JPanel();
        pieChartPanel5 = new javax.swing.JPanel();
        pieChartPanel6 = new javax.swing.JPanel();
        pieChartPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Báo cáo thống kê");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlPieChartMonAn.setMinimumSize(new java.awt.Dimension(300, 300));
        pnlPieChartMonAn.setPreferredSize(new java.awt.Dimension(300, 300));
        pnlPieChartMonAn.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 213, 290);
        getContentPane().add(pnlPieChartMonAn, gridBagConstraints);

        pnlPieChartKhachHang.setMinimumSize(new java.awt.Dimension(300, 300));
        pnlPieChartKhachHang.setPreferredSize(new java.awt.Dimension(300, 300));
        pnlPieChartKhachHang.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 213, 290);
        getContentPane().add(pnlPieChartKhachHang, gridBagConstraints);

        pnlBarChartDoanhThu.setMinimumSize(new java.awt.Dimension(400, 300));
        pnlBarChartDoanhThu.setName(""); // NOI18N
        pnlBarChartDoanhThu.setPreferredSize(new java.awt.Dimension(400, 300));
        pnlBarChartDoanhThu.setLayout(new java.awt.BorderLayout());

        pieChartPanel3.setLayout(new java.awt.BorderLayout());
        pnlBarChartDoanhThu.add(pieChartPanel3, java.awt.BorderLayout.CENTER);

        pieChartPanel4.setLayout(new java.awt.BorderLayout());

        pieChartPanel5.setLayout(new java.awt.BorderLayout());

        pieChartPanel6.setLayout(new java.awt.BorderLayout());

        pieChartPanel7.setLayout(new java.awt.BorderLayout());
        pieChartPanel6.add(pieChartPanel7, java.awt.BorderLayout.CENTER);

        pieChartPanel5.add(pieChartPanel6, java.awt.BorderLayout.CENTER);

        pieChartPanel4.add(pieChartPanel5, java.awt.BorderLayout.CENTER);

        pnlBarChartDoanhThu.add(pieChartPanel4, java.awt.BorderLayout.PAGE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 213, 290);
        getContentPane().add(pnlBarChartDoanhThu, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaoCaoThongKe_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pieChartPanel3;
    private javax.swing.JPanel pieChartPanel4;
    private javax.swing.JPanel pieChartPanel5;
    private javax.swing.JPanel pieChartPanel6;
    private javax.swing.JPanel pieChartPanel7;
    private javax.swing.JPanel pnlBarChartDoanhThu;
    private javax.swing.JPanel pnlPieChartKhachHang;
    private javax.swing.JPanel pnlPieChartMonAn;
    // End of variables declaration//GEN-END:variables
}
