/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.DonGoi_BUS;
import BUS.MonAn_BUS;
import Constraints.TinhTrangMonAnConstraints;
import DTO.Ban.CreateDonGoi_DTO;
import DTO.Ban.DonGoi_DTO;
import DTO.Ban.UpdateDonGoi_DTO;
import DTO.MonAn.MonAnFull_DTO;
import com.mycompany.quanlynhahang.Price;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.kordamp.ikonli.materialdesign.MaterialDesign;
import org.kordamp.ikonli.materialdesign2.MaterialDesignI;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author dinhn
 */
public class DatMon_GUI extends javax.swing.JFrame {
    private MonAn_BUS monAn_BUS;
    private DonGoi_BUS donGoi_BUS;
    private int idMonAn;
    private int idBan;
    private boolean dangThemMon;
    private DonGoi_DTO donGoi_DTO;
    /**
     * Creates new form ThemMonAn_GUI
     * @param idMonAn
     */
    public DatMon_GUI(int idBan, int idMonAn) {
        initComponents();
        this.idMonAn = idMonAn;
        this.idBan = idBan;
        monAn_BUS = new MonAn_BUS();
        donGoi_BUS = new DonGoi_BUS();
        
        if(donGoi_BUS.daTonTai(idBan, idMonAn)){
            dangThemMon = false;
            this.setTitle("Sửa đơn gọi");
            donGoi_DTO = donGoi_BUS.getDonGoiById(idBan, idMonAn);
        }
        else{
            dangThemMon = true;
        }
        
        loadMonAn();
    }

    private void loadMonAn(){
        MonAnFull_DTO monAn = monAn_BUS.getMonAnFullById(idMonAn);
        
        /*
         JLabel lblHinhAnh = new JLabel();
                
                lblHinhAnh.setIcon(new ImageIcon(newImage));
        */
        
        if (monAn.getHinhAnh() == null){
            FontIcon iconNoImage = FontIcon.of(MaterialDesignI.IMAGE_OFF,320,Color.GRAY);
            lblHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblHinhAnh.setIcon(iconNoImage);
        } else {
            ImageIcon yourImage = new ImageIcon(monAn.getHinhAnh());
            Image newImage = yourImage.getImage().getScaledInstance(400, 400, Image.SCALE_DEFAULT);
            lblHinhAnh.setIcon(new ImageIcon(newImage));
        }
        lblTenMonAn.setText(monAn.getTen());
        lblNoiDungMonAn.setText(monAn.getNoiDung());
        lblLoaiMonAn.setText(monAn.getLoaiMonAn().getTen());
        lblGia.setText(Price.formatPrice(monAn.getGia()));
        if(monAn.getGiaKhuyenMai() > 0)
            lblGiaKhuyenMai.setText(Price.formatPrice(monAn.getGiaKhuyenMai()));
        else
            lblGiaKhuyenMai.setText("");
        if(!dangThemMon){
            lblSoLuongHienTai.setText(Integer.toString(donGoi_DTO.getSoLuong()));
            spnSoLuong.setValue(donGoi_DTO.getSoLuong());
            if(donGoi_DTO.getGhiChu() != null && !donGoi_DTO.getGhiChu().isBlank())
                txaGhiChu.setText(donGoi_DTO.getGhiChu());
        }
        
        lblTinhTrangMonAn.setText(monAn.getTinhTrangMonAn().getTen());
        if(monAn.getTinhTrangMonAn().getId() == TinhTrangMonAnConstraints.HET)
            btnDatMon.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblHinhAnh = new javax.swing.JLabel();
        lblTenMonAn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblGiaKhuyenMai = new javax.swing.JLabel();
        spnSoLuong = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        btnDatMon = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaGhiChu = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lblTinhTrangMonAn = new javax.swing.JLabel();
        lblNoiDungMonAn = new javax.swing.JLabel();
        lblLoaiMonAn = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSoLuongHienTai = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm món ăn");
        setMaximumSize(new java.awt.Dimension(840, 500));
        setMinimumSize(new java.awt.Dimension(840, 500));
        setPreferredSize(new java.awt.Dimension(840, 500));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblHinhAnh.setBackground(new java.awt.Color(255, 102, 102));
        lblHinhAnh.setForeground(new java.awt.Color(153, 255, 255));
        lblHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinhAnh.setMaximumSize(new java.awt.Dimension(400, 400));
        lblHinhAnh.setMinimumSize(new java.awt.Dimension(400, 400));
        lblHinhAnh.setPreferredSize(new java.awt.Dimension(400, 400));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(lblHinhAnh, gridBagConstraints);

        lblTenMonAn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenMonAn.setText("Tàu Hủ Nóng");
        lblTenMonAn.setMaximumSize(new java.awt.Dimension(288, 40));
        lblTenMonAn.setMinimumSize(new java.awt.Dimension(288, 40));
        lblTenMonAn.setPreferredSize(new java.awt.Dimension(288, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 0, 20);
        getContentPane().add(lblTenMonAn, gridBagConstraints);

        jLabel3.setText("Giá");
        jLabel3.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel3.setMinimumSize(new java.awt.Dimension(120, 24));
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 4, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        lblGia.setText("90000VNĐ");
        lblGia.setMaximumSize(new java.awt.Dimension(120, 24));
        lblGia.setMinimumSize(new java.awt.Dimension(120, 24));
        lblGia.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 4, 20);
        getContentPane().add(lblGia, gridBagConstraints);

        jLabel5.setText("Giá khuyến mãi");
        jLabel5.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel5.setMinimumSize(new java.awt.Dimension(120, 24));
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 4, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        lblGiaKhuyenMai.setText("75000VNĐ");
        lblGiaKhuyenMai.setMaximumSize(new java.awt.Dimension(120, 24));
        lblGiaKhuyenMai.setMinimumSize(new java.awt.Dimension(120, 24));
        lblGiaKhuyenMai.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 4, 20);
        getContentPane().add(lblGiaKhuyenMai, gridBagConstraints);

        spnSoLuong.setMaximumSize(new java.awt.Dimension(120, 24));
        spnSoLuong.setMinimumSize(new java.awt.Dimension(120, 24));
        spnSoLuong.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 4, 20);
        getContentPane().add(spnSoLuong, gridBagConstraints);

        jLabel7.setText("Số lượng");
        jLabel7.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel7.setMinimumSize(new java.awt.Dimension(120, 24));
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 4, 0);
        getContentPane().add(jLabel7, gridBagConstraints);

        btnDatMon.setText("Đặt ngay");
        btnDatMon.setMaximumSize(new java.awt.Dimension(288, 40));
        btnDatMon.setMinimumSize(new java.awt.Dimension(288, 40));
        btnDatMon.setPreferredSize(new java.awt.Dimension(288, 40));
        btnDatMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDatMonMouseClicked(evt);
            }
        });
        btnDatMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatMonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 20, 20);
        getContentPane().add(btnDatMon, gridBagConstraints);

        jLabel8.setText("Ghi chú");
        jLabel8.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel8.setMinimumSize(new java.awt.Dimension(120, 24));
        jLabel8.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 4, 0);
        getContentPane().add(jLabel8, gridBagConstraints);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(234, 86));

        txaGhiChu.setColumns(20);
        txaGhiChu.setLineWrap(true);
        txaGhiChu.setRows(5);
        txaGhiChu.setMaximumSize(new java.awt.Dimension(160, 80));
        txaGhiChu.setMinimumSize(new java.awt.Dimension(160, 80));
        txaGhiChu.setPreferredSize(new java.awt.Dimension(160, 80));
        jScrollPane1.setViewportView(txaGhiChu);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 4, 20);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel1.setText("Tình trạng món");
        jLabel1.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel1.setMinimumSize(new java.awt.Dimension(120, 24));
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 4, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        lblTinhTrangMonAn.setText("Sẵn sàng");
        lblTinhTrangMonAn.setMaximumSize(new java.awt.Dimension(120, 24));
        lblTinhTrangMonAn.setMinimumSize(new java.awt.Dimension(120, 24));
        lblTinhTrangMonAn.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 4, 20);
        getContentPane().add(lblTinhTrangMonAn, gridBagConstraints);

        lblNoiDungMonAn.setText("Nội dung món ăn");
        lblNoiDungMonAn.setMaximumSize(new java.awt.Dimension(288, 48));
        lblNoiDungMonAn.setMinimumSize(new java.awt.Dimension(288, 48));
        lblNoiDungMonAn.setPreferredSize(new java.awt.Dimension(288, 48));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 20);
        getContentPane().add(lblNoiDungMonAn, gridBagConstraints);

        lblLoaiMonAn.setText("Loại");
        lblLoaiMonAn.setMaximumSize(new java.awt.Dimension(120, 24));
        lblLoaiMonAn.setMinimumSize(new java.awt.Dimension(120, 24));
        lblLoaiMonAn.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 4, 20);
        getContentPane().add(lblLoaiMonAn, gridBagConstraints);

        jLabel12.setText("Loại món ăn");
        jLabel12.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel12.setMinimumSize(new java.awt.Dimension(120, 24));
        jLabel12.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 4, 0);
        getContentPane().add(jLabel12, gridBagConstraints);

        jLabel2.setText("Số lượng món hiện tại");
        jLabel2.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel2.setMinimumSize(new java.awt.Dimension(120, 24));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 4, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        lblSoLuongHienTai.setText("0");
        lblSoLuongHienTai.setMaximumSize(new java.awt.Dimension(120, 24));
        lblSoLuongHienTai.setMinimumSize(new java.awt.Dimension(120, 24));
        lblSoLuongHienTai.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 4, 20);
        getContentPane().add(lblSoLuongHienTai, gridBagConstraints);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDatMonActionPerformed

    private void btnDatMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatMonMouseClicked
        // TODO add your handling code here:
        if (btnDatMon.isEnabled()){
            int soLuong = 0;
            try {
                soLuong = Integer.parseInt(spnSoLuong.getValue().toString());
                if(soLuong < 1){
                    throw new NumberFormatException("Số lượng món nhỏ hơn 1");
                }
            } catch (NumberFormatException e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(this, "Số lượng món ăn không hợp lệ","Error", JOptionPane.ERROR_MESSAGE);   
                return;
            }
        

            String ghiChu = null;
            if(!txaGhiChu.getText().isBlank())
                ghiChu = txaGhiChu.getText();
            if(dangThemMon){
                CreateDonGoi_DTO createDonGoi_DTO = new CreateDonGoi_DTO();  

                createDonGoi_DTO.setIdMA(idMonAn);
                createDonGoi_DTO.setIdBan(idBan);
                createDonGoi_DTO.setSoLuong(soLuong);
                createDonGoi_DTO.setGhiChu(ghiChu);

                boolean result = donGoi_BUS.createDonGoi(createDonGoi_DTO);

                if(result){
                    JOptionPane.showMessageDialog(this, "Thêm món ăn mới thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } else {            
                    JOptionPane.showMessageDialog(this, "Thêm món ăn mới thất bại","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                UpdateDonGoi_DTO updateDonGoi_DTO = new UpdateDonGoi_DTO(idBan, idMonAn, soLuong, ghiChu);

                boolean result = donGoi_BUS.updateDonGoi(updateDonGoi_DTO);

                if(result){
                    JOptionPane.showMessageDialog(this, "Sửa món ăn thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } else {            
                    JOptionPane.showMessageDialog(this, "Sửa món ăn thất bại","Thông báo", JOptionPane.INFORMATION_MESSAGE);

                }
            }
        }
        
    }//GEN-LAST:event_btnDatMonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatMon_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatMon_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatMon_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatMon_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ThemMonAn_GUI(idMonAn, idBan).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatMon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblGiaKhuyenMai;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblLoaiMonAn;
    private javax.swing.JLabel lblNoiDungMonAn;
    private javax.swing.JLabel lblSoLuongHienTai;
    private javax.swing.JLabel lblTenMonAn;
    private javax.swing.JLabel lblTinhTrangMonAn;
    private javax.swing.JSpinner spnSoLuong;
    private javax.swing.JTextArea txaGhiChu;
    // End of variables declaration//GEN-END:variables
}
