/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.DonGoi_BUS;
import BUS.MonAn_BUS;
import Constraints.TinhTrangMonAnConstraints;
import DTO.Ban.CreateDonGoi_DTO;
import DTO.Ban.DonGoi_DTO;
import DTO.MonAn.MonAnFull_DTO;
import com.mycompany.quanlynhahang.Price;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author dinhn
 */
public class DatMon_GUI extends javax.swing.JFrame {
    private MonAn_BUS monAn_BUS;
    private DonGoi_BUS donGoi_BUS;
    private int idMonAn;
    private int idBan;
    private boolean dangThemMon;
    private DonGoi_DTO donGoi_DTO;
    /**
     * Creates new form ThemMonAn_GUI
     * @param idMonAn
     */
    public DatMon_GUI(int idBan, int idMonAn) {
        initComponents();
        this.idMonAn = idMonAn;
        this.idBan = idBan;
        monAn_BUS = new MonAn_BUS();
        donGoi_BUS = new DonGoi_BUS();
        
        if(donGoi_BUS.daTonTai(idBan, idMonAn)){
            dangThemMon = false;
            this.setTitle("Sửa đơn gọi");
            donGoi_DTO = donGoi_BUS.getDonGoiById(idBan, idMonAn);
        }
        else{
            dangThemMon = true;
        }
        
        loadMonAn();
    }

    private void loadMonAn(){
        MonAnFull_DTO monAn = monAn_BUS.getMonAnFullById(idMonAn);
        
        
        lblHinhAnh.setIcon(new ImageIcon(monAn.getHinhAnh()));
        Icon i = lblHinhAnh.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getScaledInstance(lblHinhAnh.getWidth(),lblHinhAnh.getHeight(),Image.SCALE_SMOOTH);
        lblHinhAnh.setIcon(new ImageIcon(image));
        lblTenMonAn.setText(monAn.getTen());
        lblNoiDungMonAn.setText(monAn.getNoiDung());
        lblLoaiMonAn.setText(monAn.getLoaiMonAn().getTen());
        lblGia.setText(Price.formatPrice(monAn.getGia()));
        if(monAn.getGiaKhuyenMai() > 0)
            lblGiaKhuyenMai.setText(Price.formatPrice(monAn.getGiaKhuyenMai()));
        else
            lblGiaKhuyenMai.setText("");
        if(!dangThemMon){
            lblSoLuongHienTai.setText(Integer.toString(donGoi_DTO.getSoLuong()));
            if(donGoi_DTO.getGhiChu() != null && !donGoi_DTO.getGhiChu().isBlank())
                txaGhiChu.setText(donGoi_DTO.getGhiChu());
        }
        
        lblTinhTrangMonAn.setText(monAn.getTinhTrangMonAn().getTen());
        if(monAn.getTinhTrangMonAn().getId() == TinhTrangMonAnConstraints.HET)
            btnDatMon.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblHinhAnh = new javax.swing.JLabel();
        lblTenMonAn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblGiaKhuyenMai = new javax.swing.JLabel();
        spnSoLuong = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        btnDatMon = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaGhiChu = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lblTinhTrangMonAn = new javax.swing.JLabel();
        lblNoiDungMonAn = new javax.swing.JLabel();
        lblLoaiMonAn = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSoLuongHienTai = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm món ăn");
        setMaximumSize(new java.awt.Dimension(660, 460));
        setMinimumSize(new java.awt.Dimension(660, 460));
        setPreferredSize(new java.awt.Dimension(660, 460));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        getContentPane().setLayout(layout);

        lblHinhAnh.setMaximumSize(new java.awt.Dimension(200, 200));
        lblHinhAnh.setMinimumSize(new java.awt.Dimension(200, 200));
        lblHinhAnh.setPreferredSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 8);
        getContentPane().add(lblHinhAnh, gridBagConstraints);

        lblTenMonAn.setText("Tàu Hủ Nóng");
        lblTenMonAn.setMaximumSize(new java.awt.Dimension(200, 24));
        lblTenMonAn.setMinimumSize(new java.awt.Dimension(200, 24));
        lblTenMonAn.setPreferredSize(new java.awt.Dimension(200, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(lblTenMonAn, gridBagConstraints);

        jLabel3.setText("Giá");
        jLabel3.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel3.setMinimumSize(new java.awt.Dimension(120, 24));
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        lblGia.setText("90000VNĐ");
        lblGia.setMaximumSize(new java.awt.Dimension(120, 24));
        lblGia.setMinimumSize(new java.awt.Dimension(120, 24));
        lblGia.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(lblGia, gridBagConstraints);

        jLabel5.setText("Giá khuyến mãi");
        jLabel5.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel5.setMinimumSize(new java.awt.Dimension(120, 24));
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        lblGiaKhuyenMai.setText("75000VNĐ");
        lblGiaKhuyenMai.setMaximumSize(new java.awt.Dimension(120, 24));
        lblGiaKhuyenMai.setMinimumSize(new java.awt.Dimension(120, 24));
        lblGiaKhuyenMai.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(lblGiaKhuyenMai, gridBagConstraints);

        spnSoLuong.setMaximumSize(new java.awt.Dimension(120, 24));
        spnSoLuong.setMinimumSize(new java.awt.Dimension(120, 24));
        spnSoLuong.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(spnSoLuong, gridBagConstraints);

        jLabel7.setText("Số lượng");
        jLabel7.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel7.setMinimumSize(new java.awt.Dimension(120, 24));
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(jLabel7, gridBagConstraints);

        btnDatMon.setText("Đặt ngay");
        btnDatMon.setMaximumSize(new java.awt.Dimension(120, 24));
        btnDatMon.setMinimumSize(new java.awt.Dimension(120, 24));
        btnDatMon.setPreferredSize(new java.awt.Dimension(120, 24));
        btnDatMon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDatMonMouseClicked(evt);
            }
        });
        btnDatMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatMonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(btnDatMon, gridBagConstraints);

        jLabel8.setText("Ghi chú");
        jLabel8.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel8.setMinimumSize(new java.awt.Dimension(120, 24));
        jLabel8.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(jLabel8, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(234, 86));

        txaGhiChu.setColumns(20);
        txaGhiChu.setRows(5);
        txaGhiChu.setMaximumSize(new java.awt.Dimension(160, 80));
        txaGhiChu.setMinimumSize(new java.awt.Dimension(160, 80));
        txaGhiChu.setPreferredSize(new java.awt.Dimension(160, 80));
        jScrollPane1.setViewportView(txaGhiChu);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel1.setText("Tình trạng món");
        jLabel1.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel1.setMinimumSize(new java.awt.Dimension(120, 24));
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        lblTinhTrangMonAn.setText("Sẵn sàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(lblTinhTrangMonAn, gridBagConstraints);

        lblNoiDungMonAn.setText("Nội dung món ăn");
        lblNoiDungMonAn.setMaximumSize(new java.awt.Dimension(288, 48));
        lblNoiDungMonAn.setMinimumSize(new java.awt.Dimension(288, 48));
        lblNoiDungMonAn.setPreferredSize(new java.awt.Dimension(288, 48));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(lblNoiDungMonAn, gridBagConstraints);

        lblLoaiMonAn.setText("Loại");
        lblLoaiMonAn.setMaximumSize(new java.awt.Dimension(120, 24));
        lblLoaiMonAn.setMinimumSize(new java.awt.Dimension(120, 24));
        lblLoaiMonAn.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(lblLoaiMonAn, gridBagConstraints);

        jLabel12.setText("Loại món ăn");
        jLabel12.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel12.setMinimumSize(new java.awt.Dimension(120, 24));
        jLabel12.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(jLabel12, gridBagConstraints);

        jLabel2.setText("Số lượng món hiện tại");
        jLabel2.setMaximumSize(new java.awt.Dimension(120, 24));
        jLabel2.setMinimumSize(new java.awt.Dimension(120, 24));
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        lblSoLuongHienTai.setText("0");
        lblSoLuongHienTai.setMaximumSize(new java.awt.Dimension(120, 24));
        lblSoLuongHienTai.setMinimumSize(new java.awt.Dimension(120, 24));
        lblSoLuongHienTai.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        getContentPane().add(lblSoLuongHienTai, gridBagConstraints);

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDatMonActionPerformed

    private void btnDatMonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatMonMouseClicked
        // TODO add your handling code here:
        CreateDonGoi_DTO createDonGoi_DTO = new CreateDonGoi_DTO();
        
        createDonGoi_DTO.setIdMA(idMonAn);
        createDonGoi_DTO.setIdBan(idBan);
        
        int soLuong = 0;
        try {
            soLuong = Integer.parseInt(spnSoLuong.getValue().toString());
            if(soLuong < 1){
                throw new NumberFormatException("Số lượng món nhỏ hơn 1");
            }
            createDonGoi_DTO.setSoLuong(soLuong);
        } catch (NumberFormatException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Số lượng món ăn không hợp lệ","Error", JOptionPane.ERROR_MESSAGE);   
            return;
        }
        
        if(!txaGhiChu.getText().isBlank())
            createDonGoi_DTO.setGhiChu(txaGhiChu.getText());
        
        boolean result = donGoi_BUS.createDonGoi(createDonGoi_DTO);
        
        if(result){
            JOptionPane.showMessageDialog(this, "Thêm món ăn mới thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {            
            JOptionPane.showMessageDialog(this, "Thêm món ăn mới thất bại","Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
            
        
        System.out.println(spnSoLuong.getValue().toString());
    }//GEN-LAST:event_btnDatMonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatMon_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatMon_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatMon_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatMon_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ThemMonAn_GUI(idMonAn, idBan).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatMon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblGiaKhuyenMai;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblLoaiMonAn;
    private javax.swing.JLabel lblNoiDungMonAn;
    private javax.swing.JLabel lblSoLuongHienTai;
    private javax.swing.JLabel lblTenMonAn;
    private javax.swing.JLabel lblTinhTrangMonAn;
    private javax.swing.JSpinner spnSoLuong;
    private javax.swing.JTextArea txaGhiChu;
    // End of variables declaration//GEN-END:variables
}
