/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.ChucVu_BUS;
import BUS.NhanVien_BUS;
import BUS.TinhTrangNhanVien_BUS;
import DTO.NhanVien.ChucVu_DTO;
import DTO.NhanVien.CreateNhanVien_DTO;
import DTO.NhanVien.NhanVienFull_DTO;
import DTO.NhanVien.NhanVien_DTO;
import DTO.NhanVien.TinhTrangNhanVien_DTO;
import DTO.NhanVien.UpdateNhanVien_DTO;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author tuant
 */
public class QuanLyNhanVien_GUI extends javax.swing.JFrame {

    private final NhanVien_BUS nhanVien_BUS;
    private final ChucVu_BUS   chucVu_BUS;
    private final TinhTrangNhanVien_BUS tinhTrangNhanVien_BUS;
    private boolean dangThemNhanVien = true;
    
    
 
    private ArrayList<ChucVu_DTO> listChucVu;
    private ArrayList<TinhTrangNhanVien_DTO> listTinhTrangNhanVien;
    
    public QuanLyNhanVien_GUI() {
        initComponents();
        
        nhanVien_BUS = new NhanVien_BUS();
        chucVu_BUS = new ChucVu_BUS();
        tinhTrangNhanVien_BUS = new TinhTrangNhanVien_BUS();
        
        loadtableNhanVien();
        loadComboBoxChucVu();
        loadComboBoxTinhTrangNhanVien();
    }
    
    public void loadtableNhanVien (){
        ArrayList<NhanVien_DTO> listNhanVien = nhanVien_BUS.getAllNhanVien();
        String col[] = {"Mã", "Tên nhân viên", "SDT", "Chức Vụ", "Tình trạng"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        tblDanhSachNV.setModel(tableModel);
        for(NhanVien_DTO row : listNhanVien){
            Object[] data = {row.getMa(), row.getHoTen(), row.getSdt(), row.getTenChucVu(), row.getTinhTrangNhanVien()};
            tableModel.addRow(data);
        }
    }
    
    
    private void loadComboBoxChucVu(){
        listChucVu = chucVu_BUS.getAllChucVu();
        
        for (ChucVu_DTO cv : listChucVu)
        {
            cmbThemChucVu.addItem(cv.getTen());
            cmblocchucvu.addItem(cv.getTen());
           
        }
        cmblocchucvu.setSelectedIndex(-1);
    }
    
    private void loadComboBoxTinhTrangNhanVien(){
        listTinhTrangNhanVien = tinhTrangNhanVien_BUS.getAllLTinhTrangNhanVien();
        
        for(TinhTrangNhanVien_DTO ttnv : listTinhTrangNhanVien){
            cmbTinhTrangNV.addItem(ttnv.getTen());
        }        
        
        cmbTinhTrangNV.setSelectedIndex(-1);
    }
    
    private void clearTextViewNhanVien(){
        txtMaNV.setText("");
        txtDiaChiNV.setText("");
        txtEmailNV.setText("");
        txtHoTenNV.setText("");
        txtSDTNV.setText("");
        ngaysinhnhanvien.getDate();
        cmbTinhTrangNV.setSelectedIndex(-1);
        cmblocchucvu.setSelectedIndex(-1);
        cmbGioiTinhNV.setSelectedIndex(-1);
        
    } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        cmbGioiTinhNhanVien = new javax.swing.JComboBox<>();
        cmblocchucvu = new javax.swing.JComboBox<>();
        btnTimKiemNhanVien = new javax.swing.JButton();
        btnLocNhanVien = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachNV = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnThemNV = new javax.swing.JButton();
        btnSuaNV = new javax.swing.JButton();
        btnXoaNV = new javax.swing.JButton();
        pnlThemNhanVien = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtSDTNV = new javax.swing.JTextField();
        txtHoTenNV = new javax.swing.JTextField();
        txtEmailNV = new javax.swing.JTextField();
        txtDiaChiNV = new javax.swing.JTextField();
        cmbTinhTrangNV = new javax.swing.JComboBox<>();
        btnResetThemNV = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbThemChucVu = new javax.swing.JComboBox<>();
        cmbGioiTinhNV = new javax.swing.JComboBox<>();
        ngaysinhnhanvien = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        btnQuanLyChucVu = new javax.swing.JButton();
        btnImportNV = new javax.swing.JButton();
        btnExportNV = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 150), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bộ lọc danh sách nhân viên"));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 120));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nhập ID hoặc tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Giới tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Chức Vụ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jLabel3, gridBagConstraints);

        txtTenNhanVien.setMinimumSize(new java.awt.Dimension(200, 22));
        txtTenNhanVien.setPreferredSize(new java.awt.Dimension(250, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(txtTenNhanVien, gridBagConstraints);

        cmbGioiTinhNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam ", "Nữ" }));
        cmbGioiTinhNhanVien.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(cmbGioiTinhNhanVien, gridBagConstraints);

        cmblocchucvu.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel2.add(cmblocchucvu, gridBagConstraints);

        btnTimKiemNhanVien.setText("Tìm kiếm");
        btnTimKiemNhanVien.setPreferredSize(new java.awt.Dimension(121, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel2.add(btnTimKiemNhanVien, gridBagConstraints);

        btnLocNhanVien.setText("Lọc theo điều kiện");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel2.add(btnLocNhanVien, gridBagConstraints);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách nhân viên"));

        tblDanhSachNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên nhân viên", "Số diện thoại", "Chức vụ", "Tình trạng"
            }
        ));
        tblDanhSachNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachNV);
        if (tblDanhSachNV.getColumnModel().getColumnCount() > 0) {
            tblDanhSachNV.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        btnThemNV.setText("Thêm ");
        btnThemNV.setEnabled(false);
        btnThemNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemNVMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btnThemNV, gridBagConstraints);

        btnSuaNV.setText("Sửa");
        btnSuaNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaNVMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btnSuaNV, gridBagConstraints);

        btnXoaNV.setText("Xóa");
        btnXoaNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaNVMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btnXoaNV, gridBagConstraints);

        jPanel4.add(jPanel5);

        pnlThemNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm nhân viên"));
        pnlThemNhanVien.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Mã nhân viên");
        pnlThemNhanVien.add(jLabel4, new java.awt.GridBagConstraints());

        jLabel5.setText("Tình trạng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlThemNhanVien.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Chức vụ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlThemNhanVien.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Ngày sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlThemNhanVien.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Họ tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlThemNhanVien.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Giới tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlThemNhanVien.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlThemNhanVien.add(jLabel10, gridBagConstraints);

        txtMaNV.setEnabled(false);
        txtMaNV.setPreferredSize(new java.awt.Dimension(150, 22));
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        pnlThemNhanVien.add(txtMaNV, gridBagConstraints);

        txtSDTNV.setPreferredSize(new java.awt.Dimension(150, 22));
        txtSDTNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTNVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlThemNhanVien.add(txtSDTNV, gridBagConstraints);

        txtHoTenNV.setMinimumSize(new java.awt.Dimension(72, 22));
        txtHoTenNV.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlThemNhanVien.add(txtHoTenNV, gridBagConstraints);

        txtEmailNV.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlThemNhanVien.add(txtEmailNV, gridBagConstraints);

        txtDiaChiNV.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlThemNhanVien.add(txtDiaChiNV, gridBagConstraints);

        cmbTinhTrangNV.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlThemNhanVien.add(cmbTinhTrangNV, gridBagConstraints);

        btnResetThemNV.setText("Reset");
        btnResetThemNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetThemNVMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlThemNhanVien.add(btnResetThemNV, gridBagConstraints);

        btnLuu.setText("Lưu");
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlThemNhanVien.add(btnLuu, gridBagConstraints);

        jLabel11.setText("Địa chỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlThemNhanVien.add(jLabel11, gridBagConstraints);

        jLabel12.setText("SDT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlThemNhanVien.add(jLabel12, gridBagConstraints);

        cmbThemChucVu.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlThemNhanVien.add(cmbThemChucVu, gridBagConstraints);

        cmbGioiTinhNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam ", "Nữ" }));
        cmbGioiTinhNV.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlThemNhanVien.add(cmbGioiTinhNV, gridBagConstraints);

        ngaysinhnhanvien.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlThemNhanVien.add(ngaysinhnhanvien, gridBagConstraints);

        jPanel4.add(pnlThemNhanVien);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng khác"));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        btnQuanLyChucVu.setText("Quản lý chức vụ");
        btnQuanLyChucVu.setMinimumSize(new java.awt.Dimension(140, 40));
        btnQuanLyChucVu.setPreferredSize(new java.awt.Dimension(140, 40));
        btnQuanLyChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyChucVuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel7.add(btnQuanLyChucVu, gridBagConstraints);

        btnImportNV.setText("Import");
        btnImportNV.setMinimumSize(new java.awt.Dimension(80, 40));
        btnImportNV.setPreferredSize(new java.awt.Dimension(80, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel7.add(btnImportNV, gridBagConstraints);

        btnExportNV.setText("Export");
        btnExportNV.setMinimumSize(new java.awt.Dimension(80, 40));
        btnExportNV.setPreferredSize(new java.awt.Dimension(80, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel7.add(btnExportNV, gridBagConstraints);

        jPanel4.add(jPanel7);
        jPanel4.add(filler1);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void txtSDTNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTNVActionPerformed

    private void btnQuanLyChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyChucVuActionPerformed

    private void tblDanhSachNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachNVMouseClicked
        // TODO add your handling code here:
        if(dangThemNhanVien){
           return;
        }
           
        int index = tblDanhSachNV.getSelectedRow();
        TableModel model = tblDanhSachNV.getModel();
        
        String ma = model.getValueAt(index, 0).toString().trim();
        NhanVienFull_DTO result = nhanVien_BUS.getNhanVienbyMa(ma);
        
        if(result == null){
            JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int indexChucVu = -1;
        for (int i = 0; i < listChucVu.size(); i++) {
            if(result.getChucVu().getId() == listChucVu.get(i).getId())
                indexChucVu = i;
        }
        int indexTinhTrangNhanVien = -1;
        for (int i = 0; i < listTinhTrangNhanVien.size(); i++) {
            if(result.getTinhTrangNhanVien().getId() == listTinhTrangNhanVien.get(i).getId())
                indexTinhTrangNhanVien = i;
        }
        
        if(indexChucVu == -1 || indexTinhTrangNhanVien == -1){
            JOptionPane.showMessageDialog(this, "Dữ liệu bị lỗi","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int gioitinh = 1;
        
        txtMaNV.setText(result.getMa());
        txtHoTenNV.setText(result.getHoTen());
        txtDiaChiNV.setText(result.getDiaChi());
        txtEmailNV.setText(result.getEmail());
        txtSDTNV.setText(result.getSoDienThoai());
        ngaysinhnhanvien.setDate(result.getNgaySinh());
        if (result.isGioiTinhNam())
        {
            gioitinh = 0;
        }
        cmbGioiTinhNV.setSelectedIndex(gioitinh);
        cmbThemChucVu.setSelectedIndex(indexChucVu);
        cmbTinhTrangNV.setSelectedIndex(indexTinhTrangNhanVien);
        
    }//GEN-LAST:event_tblDanhSachNVMouseClicked

    private void btnThemNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemNVMouseClicked
        // TODO add your handling code here:
        btnThemNV.setEnabled(false);
        btnSuaNV.setEnabled(true);
        dangThemNhanVien = true;
        pnlThemNhanVien.setBorder(BorderFactory.createTitledBorder("Thêm nhân viên mới"));
        pnlThemNhanVien.repaint();
        clearTextViewNhanVien();
    }//GEN-LAST:event_btnThemNVMouseClicked

    private void btnSuaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaNVMouseClicked
        // TODO add your handling code here:
        btnThemNV.setEnabled(true);
        btnSuaNV.setEnabled(false);
        dangThemNhanVien = false;
        cmbGioiTinhNV.setEnabled(false);
        pnlThemNhanVien.setBorder(BorderFactory.createTitledBorder("Sửa nhân viên "));
        pnlThemNhanVien.repaint();
        clearTextViewNhanVien();
    }//GEN-LAST:event_btnSuaNVMouseClicked

    private void btnResetThemNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetThemNVMouseClicked
        // TODO add your handling code here:
          if(dangThemNhanVien){
            loadComboBoxChucVu();
            loadComboBoxTinhTrangNhanVien();
        } else {
            String ma = txtMaNV.getText();
            NhanVienFull_DTO result = nhanVien_BUS.getNhanVienbyMa(ma);

            if(result == null){
                JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int indexChucVu = -1;
        for (int i = 0; i < listChucVu.size(); i++) {
            if(result.getChucVu().getId() == listChucVu.get(i).getId())
                indexChucVu = i;
        }
        int indexTinhTrangNhanVien = -1;
        for (int i = 0; i < listTinhTrangNhanVien.size(); i++) {
            if(result.getTinhTrangNhanVien().getId() == listTinhTrangNhanVien.get(i).getId())
                indexTinhTrangNhanVien = i;
        }
        
        if(indexChucVu == -1 || indexTinhTrangNhanVien == -1){
            JOptionPane.showMessageDialog(this, "Dữ liệu bị lỗi","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int gioitinh = 1;
        
        txtMaNV.setText(result.getMa());
        txtHoTenNV.setText(result.getHoTen());
        txtDiaChiNV.setText(result.getDiaChi());
        txtEmailNV.setText(result.getEmail());
        txtSDTNV.setText(result.getSoDienThoai());
        if (result.isGioiTinhNam())
        {
            gioitinh = 0;
        }
        cmbGioiTinhNV.setSelectedIndex(gioitinh);
        cmbThemChucVu.setSelectedIndex(indexChucVu);
        cmbTinhTrangNV.setSelectedIndex(indexTinhTrangNhanVien);
        }
    }//GEN-LAST:event_btnResetThemNVMouseClicked

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:
        int indexChucVu = cmbThemChucVu.getSelectedIndex();
        if(indexChucVu < 0)
            JOptionPane.showMessageDialog(this, "Chưa chọn chức vụ","Error", JOptionPane.ERROR_MESSAGE);

        int indexTinhTrangNhanVien = cmbTinhTrangNV.getSelectedIndex();
        if(indexTinhTrangNhanVien < 0)
            JOptionPane.showMessageDialog(this, "Chưa chọn tình trạng nhân viên","Error", JOptionPane.ERROR_MESSAGE);         

        int idChucVu = listChucVu.get(indexChucVu).getId();
        int idTinhTrangNhanVien = listTinhTrangNhanVien.get(indexTinhTrangNhanVien).getId();
        
        String ma = txtMaNV.getText().trim();
        if(ma.isBlank())
            JOptionPane.showMessageDialog(this, "Tên nhân viên không được để trống","Error", JOptionPane.ERROR_MESSAGE);
        String HoTen = txtHoTenNV.getText().trim();
        if(HoTen.isBlank())
            JOptionPane.showMessageDialog(this, "Tên nhân viên không được để trống","Error", JOptionPane.ERROR_MESSAGE);
        String DiaChi = txtDiaChiNV.getText().trim();
        if(DiaChi.isBlank())
            JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống","Error", JOptionPane.ERROR_MESSAGE);
        String email = txtEmailNV.getText().trim();
        if(email.isBlank())
            JOptionPane.showMessageDialog(this, "Email không được để trống","Error", JOptionPane.ERROR_MESSAGE);
        String sdt = txtSDTNV.getText().trim();
        if(sdt.isBlank())
            JOptionPane.showMessageDialog(this, "SDT không được để trống","Error", JOptionPane.ERROR_MESSAGE);
        
        boolean gioitinh = false;
        if (cmbGioiTinhNV.getSelectedIndex() == 0){
            gioitinh = true;
        }
        Date ngaySinh;
        ngaySinh = new Date(ngaysinhnhanvien.getDate().getTime());
        
        
        if (dangThemNhanVien){
            CreateNhanVien_DTO data = new CreateNhanVien_DTO(ma, idTinhTrangNhanVien, idChucVu, HoTen, ngaySinh, gioitinh, email, sdt, DiaChi);

            boolean result = nhanVien_BUS.createNhanVien(data);
            if(result){
                JOptionPane.showMessageDialog(this, "Thêm nhân viên mới thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                clearTextViewNhanVien();  
                loadtableNhanVien();
            }            
            else
                JOptionPane.showMessageDialog(this, "Thêm nhân viên mới thất bại","Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String idnv = txtMaNV.getText();
            UpdateNhanVien_DTO data = new UpdateNhanVien_DTO(idnv, idTinhTrangNhanVien, idChucVu, HoTen, ngaySinh, email, sdt, DiaChi);
            
            boolean result = nhanVien_BUS.updateNhanVien(data);
            if(result){
                JOptionPane.showMessageDialog(this, "Sửa nhân viên thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                clearTextViewNhanVien();  
                loadtableNhanVien();
            }            
            else
                JOptionPane.showMessageDialog(this, "Sửa nhân viên thất bại","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLuuMouseClicked

    private void btnXoaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaNVMouseClicked
        // TODO add your handling code here:
         int total = tblDanhSachNV.getSelectedRowCount();
        TableModel model = tblDanhSachNV.getModel();
        if(total < 1)
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhân viên muốn xóa","Error", JOptionPane.ERROR_MESSAGE);
        
        int confirm = JOptionPane.showConfirmDialog(null, 
                "Bạn có chắc chắn muốn xóa " + total + " nhân viên không ?", "Xóa dữ liệu nhân viên!", JOptionPane.OK_CANCEL_OPTION);
        
        if(confirm == JOptionPane.CANCEL_OPTION)
            return;
        
        if(total == 1){
            int index = tblDanhSachNV.getSelectedRow();

            String ma = model.getValueAt(index, 0).toString();

            boolean result = nhanVien_BUS.deleteNhanVien(ma);
            if(result){
                JOptionPane.showMessageDialog(this, "Xóa 1 nhân viên thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                
            }            
            else
                JOptionPane.showMessageDialog(this, "Xóa thất bại","Error", JOptionPane.ERROR_MESSAGE);
        } 
        clearTextViewNhanVien();  
        loadtableNhanVien();
    }//GEN-LAST:event_btnXoaNVMouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportNV;
    private javax.swing.JButton btnImportNV;
    private javax.swing.JButton btnLocNhanVien;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnQuanLyChucVu;
    private javax.swing.JButton btnResetThemNV;
    private javax.swing.JButton btnSuaNV;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnTimKiemNhanVien;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.JComboBox<String> cmbGioiTinhNV;
    private javax.swing.JComboBox<String> cmbGioiTinhNhanVien;
    private javax.swing.JComboBox<String> cmbThemChucVu;
    private javax.swing.JComboBox<String> cmbTinhTrangNV;
    private javax.swing.JComboBox<String> cmblocchucvu;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser ngaysinhnhanvien;
    private javax.swing.JPanel pnlThemNhanVien;
    private javax.swing.JTable tblDanhSachNV;
    private javax.swing.JTextField txtDiaChiNV;
    private javax.swing.JTextField txtEmailNV;
    private javax.swing.JTextField txtHoTenNV;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDTNV;
    private javax.swing.JTextField txtTenNhanVien;
    // End of variables declaration//GEN-END:variables
}
