
package GUI;

import BUS.ChucVu_BUS;
import BUS.NhanVien_BUS;
import BUS.TinhTrangNhanVien_BUS;
import Constraints.GioiTinhConstraints;
import Constraints.TinhTrangNhanVienConstraints;
import DTO.NhanVien.ChucVu_DTO;
import DTO.NhanVien.CreateNhanVien_DTO;
import DTO.NhanVien.NhanVienFull_DTO;
import DTO.NhanVien.NhanVien_DTO;
import DTO.NhanVien.SearchNhanVien_DTO;
import DTO.NhanVien.TinhTrangNhanVien_DTO;
import DTO.NhanVien.UpdateNhanVien_DTO;
import com.mycompany.quanlynhahang.CheckHopLe;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.Period;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author tuant
 */
public class QuanLyNhanVien_GUI extends javax.swing.JFrame {

    private final NhanVien_BUS nhanVien_BUS;
    private final ChucVu_BUS   chucVu_BUS;
    private final TinhTrangNhanVien_BUS tinhTrangNhanVien_BUS;
    private boolean dangThemNhanVien = true;
    
    private QuanLyChucVu_GUI quanLyChucVu_GUI;
    private QuanLyQuyen_GUI quanLyQuyen_GUI;
    private DoiMatKhau_GUI doiMatKhau_GUI;
    
     private ArrayList<NhanVienFull_DTO> listNhanVien;
    
    private ArrayList<ChucVu_DTO> listChucVu;
    private ArrayList<TinhTrangNhanVien_DTO> listTinhTrangNhanVien;
    
    public QuanLyNhanVien_GUI() {
        initComponents();
        
        nhanVien_BUS = new NhanVien_BUS();
        chucVu_BUS = new ChucVu_BUS();
        tinhTrangNhanVien_BUS = new TinhTrangNhanVien_BUS();
        
        loadtableNhanVien();
        loadComboBoxChucVu();
        loadComboBoxTinhTrangNhanVien();
    }
    
    public void loadtableNhanVien (){
        ArrayList<NhanVien_DTO> listNhanVien = nhanVien_BUS.getAllNhanVien();
        String col[] = {"Mã nhân viên", "Tên nhân viên", "SDT", "Chức Vụ", "Tình trạng"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        tblDanhSachNV.setModel(tableModel);
        for(NhanVien_DTO row : listNhanVien){
            Object[] data = {row.getMa(), row.getHoTen(), row.getSdt(), row.getTenChucVu(), row.getTinhTrangNhanVien()};
            tableModel.addRow(data);
        }
    }
    
     private void loadTableNhanVien(ArrayList<NhanVien_DTO> dataTable){
        
        ArrayList<NhanVien_DTO> listNhanVien = dataTable;
        String col[] = {"Mã nhân viên", "Tên nhân viên", "SDT", "Chức Vụ", "Tình Trạng"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        tblDanhSachNV.setModel(tableModel);
        for(NhanVien_DTO row : listNhanVien){
            Object[] data = {row.getMa(), row.getHoTen(), row.getSdt(), row.getTenChucVu(), row.getTinhTrangNhanVien()};
            tableModel.addRow(data);
        }
    }
    
    
    
    private void loadComboBoxChucVu(){
        listChucVu = chucVu_BUS.getAllChucVu();
        
        for (ChucVu_DTO cv : listChucVu)
        {
            cmbThemChucVu.addItem(cv.getTen());
            cmblocchucvu.addItem(cv.getTen());
           
        }
        cmbThemChucVu.setSelectedIndex(0);
        cmblocchucvu.setSelectedIndex(0);
    }
    
    private void loadComboBoxTinhTrangNhanVien(){
        listTinhTrangNhanVien = tinhTrangNhanVien_BUS.getAllLTinhTrangNhanVien();
        
        for(TinhTrangNhanVien_DTO ttnv : listTinhTrangNhanVien){
            cmbTinhTrangNV.addItem(ttnv.getTen());
        }        
        
        cmbTinhTrangNV.setSelectedIndex(0);
    }
    
    private void clearTextViewNhanVien(){
        txtMaNV.setText("");
        txtDiaChiNV.setText("");
        txtEmailNV.setText("");
        txtHoTenNV.setText("");
        txtSDTNV.setText("");
        ngaysinhnhanvien.getDate();
        cmbTinhTrangNV.setSelectedIndex(-1);
        cmblocchucvu.setSelectedIndex(-1);
        cmbGioiTinhNV.setSelectedIndex(-1);
        
    } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaOrTen = new javax.swing.JTextField();
        cmbTimKiemGioiTinhNhanVien = new javax.swing.JComboBox<>();
        cmblocchucvu = new javax.swing.JComboBox<>();
        btnTimKiemNhanVien = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cmbTinhTrangNhanVienSearch = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachNV = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnThemNV = new javax.swing.JButton();
        btnSuaNV = new javax.swing.JButton();
        btnXoaNV = new javax.swing.JButton();
        pnlThemNhanVien = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtSDTNV = new javax.swing.JTextField();
        txtHoTenNV = new javax.swing.JTextField();
        txtEmailNV = new javax.swing.JTextField();
        txtDiaChiNV = new javax.swing.JTextField();
        cmbTinhTrangNV = new javax.swing.JComboBox<>();
        btnResetThemNV = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbThemChucVu = new javax.swing.JComboBox<>();
        cmbGioiTinhNV = new javax.swing.JComboBox<>();
        ngaysinhnhanvien = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        btnQuanLyChucVu = new javax.swing.JButton();
        btnImportNV = new javax.swing.JButton();
        btnExportNV = new javax.swing.JButton();
        btnPhanQuyen = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 150), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý nhân viên");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bộ lọc danh sách nhân viên"));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 120));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nhập Mã hoặc Tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Giới tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Chức Vụ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jLabel3, gridBagConstraints);

        txtMaOrTen.setMinimumSize(new java.awt.Dimension(200, 22));
        txtMaOrTen.setPreferredSize(new java.awt.Dimension(250, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(txtMaOrTen, gridBagConstraints);

        cmbTimKiemGioiTinhNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả", "Nam", "Nữ" }));
        cmbTimKiemGioiTinhNhanVien.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(cmbTimKiemGioiTinhNhanVien, gridBagConstraints);

        cmblocchucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));
        cmblocchucvu.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel2.add(cmblocchucvu, gridBagConstraints);

        btnTimKiemNhanVien.setText("Tìm kiếm");
        btnTimKiemNhanVien.setMaximumSize(new java.awt.Dimension(121, 70));
        btnTimKiemNhanVien.setMinimumSize(new java.awt.Dimension(121, 70));
        btnTimKiemNhanVien.setPreferredSize(new java.awt.Dimension(121, 70));
        btnTimKiemNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemNhanVienMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel2.add(btnTimKiemNhanVien, gridBagConstraints);

        jLabel13.setText("Tình trạng nhân viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel2.add(jLabel13, gridBagConstraints);

        cmbTinhTrangNhanVienSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đang hoạt động", "Tạm nghỉ ", "Đã nghỉ" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(cmbTinhTrangNhanVienSearch, gridBagConstraints);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách nhân viên"));

        tblDanhSachNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên nhân viên", "Số diện thoại", "Chức vụ", "Tình trạng"
            }
        )

    );
    tblDanhSachNV.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblDanhSachNVMouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            tblDanhSachNVMouseEntered(evt);
        }
    });
    jScrollPane1.setViewportView(tblDanhSachNV);
    if (tblDanhSachNV.getColumnModel().getColumnCount() > 0) {
        tblDanhSachNV.getColumnModel().getColumn(1).setPreferredWidth(200);
    }

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel1.add(jPanel3);

    getContentPane().add(jPanel1);

    jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
    jPanel5.setLayout(new java.awt.GridBagLayout());

    btnThemNV.setText("Thêm ");
    btnThemNV.setEnabled(false);
    btnThemNV.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnThemNVMouseClicked(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
    jPanel5.add(btnThemNV, gridBagConstraints);

    btnSuaNV.setText("Sửa");
    btnSuaNV.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnSuaNVMouseClicked(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
    jPanel5.add(btnSuaNV, gridBagConstraints);

    btnXoaNV.setText("Xóa");
    btnXoaNV.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnXoaNVMouseClicked(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
    jPanel5.add(btnXoaNV, gridBagConstraints);

    jPanel4.add(jPanel5);

    pnlThemNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm nhân viên"));
    pnlThemNhanVien.setLayout(new java.awt.GridBagLayout());

    jLabel4.setText("Mã nhân viên");
    pnlThemNhanVien.add(jLabel4, new java.awt.GridBagConstraints());

    jLabel5.setText("Tình trạng");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
    pnlThemNhanVien.add(jLabel5, gridBagConstraints);

    jLabel6.setText("Chức vụ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
    pnlThemNhanVien.add(jLabel6, gridBagConstraints);

    jLabel7.setText("Ngày sinh");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
    pnlThemNhanVien.add(jLabel7, gridBagConstraints);

    jLabel8.setText("Họ tên");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
    pnlThemNhanVien.add(jLabel8, gridBagConstraints);

    jLabel9.setText("Giới tính");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
    pnlThemNhanVien.add(jLabel9, gridBagConstraints);

    jLabel10.setText("Email");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
    pnlThemNhanVien.add(jLabel10, gridBagConstraints);

    txtMaNV.setPreferredSize(new java.awt.Dimension(150, 22));
    txtMaNV.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtMaNVActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
    pnlThemNhanVien.add(txtMaNV, gridBagConstraints);

    txtSDTNV.setPreferredSize(new java.awt.Dimension(150, 22));
    txtSDTNV.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtSDTNVActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
    pnlThemNhanVien.add(txtSDTNV, gridBagConstraints);

    txtHoTenNV.setMinimumSize(new java.awt.Dimension(72, 22));
    txtHoTenNV.setPreferredSize(new java.awt.Dimension(150, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
    pnlThemNhanVien.add(txtHoTenNV, gridBagConstraints);

    txtEmailNV.setPreferredSize(new java.awt.Dimension(150, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
    pnlThemNhanVien.add(txtEmailNV, gridBagConstraints);

    txtDiaChiNV.setPreferredSize(new java.awt.Dimension(150, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
    pnlThemNhanVien.add(txtDiaChiNV, gridBagConstraints);

    cmbTinhTrangNV.setPreferredSize(new java.awt.Dimension(150, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
    pnlThemNhanVien.add(cmbTinhTrangNV, gridBagConstraints);

    btnResetThemNV.setText("Reset");
    btnResetThemNV.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnResetThemNVMouseClicked(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
    pnlThemNhanVien.add(btnResetThemNV, gridBagConstraints);

    btnLuu.setText("Lưu");
    btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnLuuMouseClicked(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 9;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
    pnlThemNhanVien.add(btnLuu, gridBagConstraints);

    jLabel11.setText("Địa chỉ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
    pnlThemNhanVien.add(jLabel11, gridBagConstraints);

    jLabel12.setText("SDT");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
    pnlThemNhanVien.add(jLabel12, gridBagConstraints);

    cmbThemChucVu.setPreferredSize(new java.awt.Dimension(150, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
    pnlThemNhanVien.add(cmbThemChucVu, gridBagConstraints);

    cmbGioiTinhNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam ", "Nữ" }));
    cmbGioiTinhNV.setPreferredSize(new java.awt.Dimension(150, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
    pnlThemNhanVien.add(cmbGioiTinhNV, gridBagConstraints);

    ngaysinhnhanvien.setPreferredSize(new java.awt.Dimension(150, 22));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
    pnlThemNhanVien.add(ngaysinhnhanvien, gridBagConstraints);

    jPanel4.add(pnlThemNhanVien);

    jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng khác"));
    jPanel7.setLayout(new java.awt.GridBagLayout());

    btnQuanLyChucVu.setText("Quản lý chức vụ");
    btnQuanLyChucVu.setMinimumSize(new java.awt.Dimension(140, 40));
    btnQuanLyChucVu.setPreferredSize(new java.awt.Dimension(140, 40));
    btnQuanLyChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnQuanLyChucVuMouseClicked(evt);
        }
    });
    btnQuanLyChucVu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnQuanLyChucVuActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
    jPanel7.add(btnQuanLyChucVu, gridBagConstraints);

    btnImportNV.setText("Import");
    btnImportNV.setMinimumSize(new java.awt.Dimension(80, 40));
    btnImportNV.setPreferredSize(new java.awt.Dimension(80, 40));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
    jPanel7.add(btnImportNV, gridBagConstraints);

    btnExportNV.setText("Export");
    btnExportNV.setMinimumSize(new java.awt.Dimension(80, 40));
    btnExportNV.setPreferredSize(new java.awt.Dimension(80, 40));
    btnExportNV.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnExportNVMouseClicked(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
    jPanel7.add(btnExportNV, gridBagConstraints);

    btnPhanQuyen.setText("Phân quyền tài khoản");
    btnPhanQuyen.setMinimumSize(new java.awt.Dimension(140, 40));
    btnPhanQuyen.setPreferredSize(new java.awt.Dimension(140, 40));
    btnPhanQuyen.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnPhanQuyenMouseClicked(evt);
        }
    });
    btnPhanQuyen.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnPhanQuyenActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    jPanel7.add(btnPhanQuyen, gridBagConstraints);

    btnDoiMatKhau.setText("Đổi mật khẩu");
    btnDoiMatKhau.setMinimumSize(new java.awt.Dimension(140, 40));
    btnDoiMatKhau.setPreferredSize(new java.awt.Dimension(140, 40));
    btnDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btnDoiMatKhauMouseClicked(evt);
        }
    });
    btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnDoiMatKhauActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
    jPanel7.add(btnDoiMatKhau, gridBagConstraints);

    jPanel4.add(jPanel7);
    jPanel4.add(filler1);

    getContentPane().add(jPanel4);

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void txtSDTNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTNVActionPerformed

    private void btnQuanLyChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyChucVuActionPerformed

    private void tblDanhSachNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachNVMouseClicked
        // TODO add your handling code here:
        if(dangThemNhanVien){
           return;
        }
           
        int index = tblDanhSachNV.getSelectedRow();
        TableModel model = tblDanhSachNV.getModel();
        
        String ma = model.getValueAt(index, 0).toString().trim();
        NhanVienFull_DTO result = nhanVien_BUS.getNhanVienbyMa(ma);
        
        if(result == null){
            JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int indexChucVu = -1;
        for (int i = 0; i < listChucVu.size(); i++) {
            if(result.getChucVu().getId() == listChucVu.get(i).getId())
                indexChucVu = i;
        }
        int indexTinhTrangNhanVien = -1;
        for (int i = 0; i < listTinhTrangNhanVien.size(); i++) {
            if(result.getTinhTrangNhanVien().getId() == listTinhTrangNhanVien.get(i).getId())
                indexTinhTrangNhanVien = i;
        }
        
        if(indexChucVu == -1 || indexTinhTrangNhanVien == -1){
            JOptionPane.showMessageDialog(this, "Dữ liệu bị lỗi","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int gioitinh = 1;
        
        txtMaNV.setText(result.getMa());
        txtHoTenNV.setText(result.getHoTen());
        txtDiaChiNV.setText(result.getDiaChi());
        txtEmailNV.setText(result.getEmail());
        txtSDTNV.setText(result.getSoDienThoai());
        ngaysinhnhanvien.setDate(result.getNgaySinh());
        if (result.isGioiTinhNam())
        {
            gioitinh = 0;
        }
        cmbGioiTinhNV.setSelectedIndex(gioitinh);
        cmbThemChucVu.setSelectedIndex(indexChucVu);
        cmbTinhTrangNV.setSelectedIndex(indexTinhTrangNhanVien);
        
        
        
    }//GEN-LAST:event_tblDanhSachNVMouseClicked

    private void btnThemNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemNVMouseClicked
        // TODO add your handling code here:
        btnThemNV.setEnabled(false);
        btnSuaNV.setEnabled(true);
        dangThemNhanVien = true;
        cmbGioiTinhNV.setEnabled(true);
        txtMaNV.setEnabled(true);
        pnlThemNhanVien.setBorder(BorderFactory.createTitledBorder("Thêm nhân viên mới"));
        pnlThemNhanVien.repaint();
        clearTextViewNhanVien();
    }//GEN-LAST:event_btnThemNVMouseClicked

    private void btnSuaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaNVMouseClicked
        // TODO add your handling code here:
        btnThemNV.setEnabled(true);
        btnSuaNV.setEnabled(false);
        dangThemNhanVien = false;
        cmbGioiTinhNV.setEnabled(false);
        pnlThemNhanVien.setBorder(BorderFactory.createTitledBorder("Sửa nhân viên "));
        pnlThemNhanVien.repaint();
        txtMaNV.setEnabled(false);
        clearTextViewNhanVien();
    }//GEN-LAST:event_btnSuaNVMouseClicked

    private void btnResetThemNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetThemNVMouseClicked
        // TODO add your handling code here:
          if(dangThemNhanVien){
            loadComboBoxChucVu();
            loadComboBoxTinhTrangNhanVien();
        } else {
            String ma = txtMaNV.getText();
            NhanVienFull_DTO result = nhanVien_BUS.getNhanVienbyMa(ma);

            if(result == null){
                JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int indexChucVu = -1;
        for (int i = 0; i < listChucVu.size(); i++) {
            if(result.getChucVu().getId() == listChucVu.get(i).getId())
                indexChucVu = i;
        }
        int indexTinhTrangNhanVien = -1;
        for (int i = 0; i < listTinhTrangNhanVien.size(); i++) {
            if(result.getTinhTrangNhanVien().getId() == listTinhTrangNhanVien.get(i).getId())
                indexTinhTrangNhanVien = i;
        }
        
        if(indexChucVu == -1 || indexTinhTrangNhanVien == -1){
            JOptionPane.showMessageDialog(this, "Dữ liệu bị lỗi","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int gioitinh = 0;
        
        txtMaNV.setText(result.getMa());
        txtHoTenNV.setText(result.getHoTen());
        txtDiaChiNV.setText(result.getDiaChi());
        txtEmailNV.setText(result.getEmail());
        txtSDTNV.setText(result.getSoDienThoai());
        if (!(result.isGioiTinhNam()))
        {
            gioitinh = 1;
        }
        cmbGioiTinhNV.setSelectedIndex(gioitinh);
        cmbThemChucVu.setSelectedIndex(indexChucVu);
        cmbTinhTrangNV.setSelectedIndex(indexTinhTrangNhanVien);
        }
    }//GEN-LAST:event_btnResetThemNVMouseClicked

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:
        int indexChucVu = cmbThemChucVu.getSelectedIndex();
        if(indexChucVu < 0)
            JOptionPane.showMessageDialog(this, "Chưa chọn chức vụ","Error", JOptionPane.ERROR_MESSAGE);

        int indexTinhTrangNhanVien = cmbTinhTrangNV.getSelectedIndex();
        if(indexTinhTrangNhanVien < 0)
            JOptionPane.showMessageDialog(this, "Chưa chọn tình trạng nhân viên","Error", JOptionPane.ERROR_MESSAGE);         

        int idChucVu = listChucVu.get(indexChucVu).getId();
        int idTinhTrangNhanVien = listTinhTrangNhanVien.get(indexTinhTrangNhanVien).getId();
        
        String ma = txtMaNV.getText().trim();
        
        if(ma.isBlank())
            JOptionPane.showMessageDialog(this, "Mã nhân viên không được để trống","Error", JOptionPane.ERROR_MESSAGE);
        
        String HoTen = txtHoTenNV.getText().trim();
        if(HoTen.isBlank())
            JOptionPane.showMessageDialog(this, "Tên nhân viên không được để trống","Error", JOptionPane.ERROR_MESSAGE);
        
        String DiaChi = txtDiaChiNV.getText().trim();
        if(DiaChi.isBlank())
            JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống","Error", JOptionPane.ERROR_MESSAGE);
        
       String email = txtEmailNV.getText().trim();
        if(!CheckHopLe.checkEmail(email)){
            JOptionPane.showMessageDialog(this, "Email không hợp lệ","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String sdt = txtSDTNV.getText().trim();
        if(!CheckHopLe.checkSoDienThoai(sdt)){
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean gioitinh = false;
        if (cmbGioiTinhNV.getSelectedIndex() == 0){
            gioitinh = true;
        }
        
        Timestamp ngaySinh;
        ngaySinh = new Timestamp(ngaysinhnhanvien.getDate().getTime());
        int tuoi = Period.between(ngaySinh.toLocalDateTime().toLocalDate(), LocalDate.now()).getYears();
        if(tuoi < 18){
            JOptionPane.showMessageDialog(this, "Nhân viên phải từ 18 tuổi trở lên","Error", JOptionPane.ERROR_MESSAGE);
            return;            
        }
        
        if (dangThemNhanVien){
            CreateNhanVien_DTO data = new CreateNhanVien_DTO(ma, idTinhTrangNhanVien, idChucVu, HoTen, ngaySinh, gioitinh, email, sdt, DiaChi);

            boolean result = nhanVien_BUS.createNhanVien(data);
            if(result){
                JOptionPane.showMessageDialog(this, "Thêm nhân viên mới thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                clearTextViewNhanVien();  
                loadtableNhanVien();
            }            
            else
                JOptionPane.showMessageDialog(this, "Thêm nhân viên mới thất bại, check lại thông tin đã thêm","Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String idnv = txtMaNV.getText();
            UpdateNhanVien_DTO data = new UpdateNhanVien_DTO(idnv, idTinhTrangNhanVien, idChucVu, HoTen, ngaySinh, email, sdt, DiaChi);
            
            boolean result = nhanVien_BUS.updateNhanVien(data);
            if(result){
                JOptionPane.showMessageDialog(this, "Sửa nhân viên thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                clearTextViewNhanVien();  
                loadtableNhanVien();
            }            
            else
                JOptionPane.showMessageDialog(this, "Sửa nhân viên thất bại","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLuuMouseClicked

    private void btnXoaNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaNVMouseClicked
        // TODO add your handling code here:
         int total = tblDanhSachNV.getSelectedRowCount();
        TableModel model = tblDanhSachNV.getModel();
        if(total < 1)
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhân viên muốn xóa","Error", JOptionPane.ERROR_MESSAGE);
        
        int confirm = JOptionPane.showConfirmDialog(null, 
                "Bạn có chắc chắn muốn xóa " + total + " nhân viên không ?", "Xóa dữ liệu nhân viên!", JOptionPane.OK_CANCEL_OPTION);
        
        if(confirm == JOptionPane.CANCEL_OPTION)
            return;
        
        if(total == 1){
            int index = tblDanhSachNV.getSelectedRow();

            String ma = model.getValueAt(index, 0).toString();

            boolean result = nhanVien_BUS.deleteNhanVien(ma);
            if(result){
                JOptionPane.showMessageDialog(this, "Xóa 1 nhân viên thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                
            }            
            else
                JOptionPane.showMessageDialog(this, "Xóa thất bại","Error", JOptionPane.ERROR_MESSAGE);
        } 
        clearTextViewNhanVien();  
        loadtableNhanVien();
    }//GEN-LAST:event_btnXoaNVMouseClicked

    private void btnQuanLyChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyChucVuMouseClicked
        // TODO add your handling code here:
        if(quanLyChucVu_GUI == null){
            quanLyChucVu_GUI = new QuanLyChucVu_GUI();
            quanLyChucVu_GUI.setVisible(true);
        } else {
            quanLyChucVu_GUI.setState(JFrame.NORMAL);
            quanLyChucVu_GUI.toFront();
        }
    }//GEN-LAST:event_btnQuanLyChucVuMouseClicked

    private void btnPhanQuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhanQuyenMouseClicked
        // TODO add your handling code here:
        if(quanLyQuyen_GUI == null || !quanLyQuyen_GUI.isDisplayable()){
            quanLyQuyen_GUI = new QuanLyQuyen_GUI();
            quanLyQuyen_GUI.setVisible(true);
        } else {
            quanLyQuyen_GUI.setState(JFrame.NORMAL);
            quanLyQuyen_GUI.toFront();
        }
    }//GEN-LAST:event_btnPhanQuyenMouseClicked

    private void btnPhanQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhanQuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPhanQuyenActionPerformed

    private void btnDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoiMatKhauMouseClicked
        // TODO add your handling code here:
        if(doiMatKhau_GUI == null || !doiMatKhau_GUI.isDisplayable()){
            doiMatKhau_GUI = new DoiMatKhau_GUI();
            doiMatKhau_GUI.setVisible(true);
        } else {
            doiMatKhau_GUI.setState(JFrame.NORMAL);
            doiMatKhau_GUI.toFront();
        }
    }//GEN-LAST:event_btnDoiMatKhauMouseClicked

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void btnTimKiemNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemNhanVienMouseClicked
        // TODO add your handling code here:
         SearchNhanVien_DTO searchNhanVien_DTO = new SearchNhanVien_DTO();
        
        String maOrName = txtMaOrTen.getText();
        if(!maOrName.isBlank()){
            searchNhanVien_DTO.setMaOrhoTen(maOrName.trim());
        }
        
        int idChucVu = cmblocchucvu.getSelectedIndex();
        if(idChucVu > 0){
            searchNhanVien_DTO.setChucVu(listChucVu.get(idChucVu -1).getId());
        }
        
        int gioiTinh = cmbTimKiemGioiTinhNhanVien.getSelectedIndex();
        switch (gioiTinh) {
            case 1 -> searchNhanVien_DTO.setGioiTinh(GioiTinhConstraints.NAM);
            case 2 -> searchNhanVien_DTO.setGioiTinh(GioiTinhConstraints.NU);
            default -> searchNhanVien_DTO.setGioiTinh(-1);       
        }
        
        int tinhTrangNhanVien = cmbTinhTrangNhanVienSearch.getSelectedIndex();
        switch (tinhTrangNhanVien) {
            case 0 -> searchNhanVien_DTO.setTinhTrang(new int[]{
                TinhTrangNhanVienConstraints.DANG_HOAT_DONG, 
                TinhTrangNhanVienConstraints.TAM_NGHI});
            
            case 1 -> searchNhanVien_DTO.setTinhTrang(new int[]{
                TinhTrangNhanVienConstraints.DANG_HOAT_DONG});
            
            case 2 -> searchNhanVien_DTO.setTinhTrang(new int[]{
                TinhTrangNhanVienConstraints.TAM_NGHI});   
            
            case 3 -> searchNhanVien_DTO.setTinhTrang(new int[]{
                TinhTrangNhanVienConstraints.DA_NGHI});   
        }
       
        ArrayList<NhanVien_DTO> result = nhanVien_BUS.searchNhanVien(searchNhanVien_DTO);
        loadTableNhanVien(result);
    }//GEN-LAST:event_btnTimKiemNhanVienMouseClicked

    
    
    private void btnExportNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportNVMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnExportNVMouseClicked

    private void tblDanhSachNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachNVMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDanhSachNVMouseEntered

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnExportNV;
    private javax.swing.JButton btnImportNV;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnPhanQuyen;
    private javax.swing.JButton btnQuanLyChucVu;
    private javax.swing.JButton btnResetThemNV;
    private javax.swing.JButton btnSuaNV;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnTimKiemNhanVien;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.JComboBox<String> cmbGioiTinhNV;
    private javax.swing.JComboBox<String> cmbThemChucVu;
    private javax.swing.JComboBox<String> cmbTimKiemGioiTinhNhanVien;
    private javax.swing.JComboBox<String> cmbTinhTrangNV;
    private javax.swing.JComboBox<String> cmbTinhTrangNhanVienSearch;
    private javax.swing.JComboBox<String> cmblocchucvu;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser ngaysinhnhanvien;
    private javax.swing.JPanel pnlThemNhanVien;
    private javax.swing.JTable tblDanhSachNV;
    private javax.swing.JTextField txtDiaChiNV;
    private javax.swing.JTextField txtEmailNV;
    private javax.swing.JTextField txtHoTenNV;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaOrTen;
    private javax.swing.JTextField txtSDTNV;
    // End of variables declaration//GEN-END:variables
}
