/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.KhachHang_BUS;
import BUS.LoaiKhachHang_BUS;
import Constraints.GioiTinhConstraints;
import DAO.KhachHang_DAO;
import DAO.LoaiKhachHang_DAO;
import DTO.KhachHang.CreateKhachHang_DTO;
import DTO.KhachHang.KhachHangFull_DTO;
import DTO.KhachHang.KhachHang_DTO;
import DTO.KhachHang.LoaiKhachHang_DTO;
import DTO.KhachHang.UpdateKhachHang_DTO;
import DTO.KhachHang.SearchKhachHang_DTO;
import com.mycompany.quanlynhahang.CheckHopLe;
import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.Period;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
/**
 *
 * @author tuant
 */
public class QuanLyKhachHang_GUI extends javax.swing.JFrame {
    private final LoaiKhachHang_BUS loaiKhach_BUS;
    private final KhachHang_BUS khachHang_BUS;
    
    private boolean dangThemKhachHang = true;
    
    private QuanLyLoaiKhachHang_GUI quanLyLoaiKhachHang_GUI;
    
    private ArrayList<LoaiKhachHang_DTO> listLoaiKhach;
    /**
     * Creates new form QuanLyKhachHang_GUI
     */
    public QuanLyKhachHang_GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        khachHang_BUS = new KhachHang_BUS();
        loaiKhach_BUS = new LoaiKhachHang_BUS();
        
        loadTableKhachHang();
        loadComboBoxTimKiemLoaiKH();
        loadComboBoxThemSuaLoaiKH();
        clearThemSuaKhachHang();
        
    }
    private void loadTableKhachHang(){
        ArrayList<KhachHang_DTO> listKhachHang = khachHang_BUS.getAllKhachHang();
        String col[] = {"ID", "Tên khách hàng", "Số diện thoại ", "Điểm tích lũy ", "Loại khách hàng "};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        tblKhachHang.setModel(tableModel);
        for(KhachHang_DTO row : listKhachHang){
            Object[] data = {row.id(), row.id(), row.sdt(), row.diemTichLuy(), row.loaiKhachHang()};
            tableModel.addRow(data);
        }
    }
    public void loadTableKhachHang(ArrayList<KhachHang_DTO> dataTable){
        
        ArrayList<KhachHang_DTO> listKhachHang = dataTable;
        String col[] = {"ID", "Tên khách hàng", "Số diện thoại ", "Điểm tích lũy ", "Loại khách hàng "};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        tblKhachHang.setModel(tableModel);
        for(KhachHang_DTO row : listKhachHang){
            Object[] data = {row.id(), row.id(), row.sdt(), row.diemTichLuy(), row.loaiKhachHang()};
            tableModel.addRow(data);
        }
    }
    
    private void loadComboBoxTimKiemLoaiKH(){
        listLoaiKhach = loaiKhach_BUS.getAllLoaiKhachHang();        
        
        for(LoaiKhachHang_DTO loaiBan : listLoaiKhach){
            cmbTimKiemLoaiKH.addItem(loaiBan.getTen());
        }      
        
        cmbTimKiemLoaiKH.setSelectedIndex(0);
    }
    private void loadComboBoxThemSuaLoaiKH(){
        listLoaiKhach = loaiKhach_BUS.getAllLoaiKhachHang();        
        
        for(LoaiKhachHang_DTO loaiBan : listLoaiKhach){
            cmbThemSuaLoaiKH.addItem(loaiBan.getTen());
        }      
        
        cmbThemSuaLoaiKH.setSelectedIndex(0);
    }
    
    private void clearThemSuaKhachHang(){
        txtIDKH.setText("");
        cmbThemSuaLoaiKH.setSelectedIndex(0);
        txtHoTen.setText("");
        txtSDT.setText("");
        txtDiemTichLuy.setText("0");
        txtEmail.setText("");
        jdcNgaySinh.setDate(new Date());
    }
    
    private void clearSearchBox(){
        txtSearchIdName.setText("");
        cmbTimKiemGioiTinh.setSelectedIndex(0);
        cmbTimKiemLoaiKH.setSelectedIndex(0);
        txtTimKiemSDT.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSearchIdName = new javax.swing.JTextField();
        cmbTimKiemLoaiKH = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbTimKiemGioiTinh = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtTimKiemSDT = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        btnResetTable = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        pnlKhachHang = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIDKH = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiemTichLuy = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cmbThemSuaLoaiKH = new javax.swing.JComboBox<>();
        btnReset = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jdcNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        cmbGioiTinhKH = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        btnQLLKH = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 200), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý khách hàng");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bộ lọc danh sách khách hàng"));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 120));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nhập ID hoặc tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel3.setText("Loại khách");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jLabel3, gridBagConstraints);

        txtSearchIdName.setMinimumSize(new java.awt.Dimension(250, 22));
        txtSearchIdName.setPreferredSize(new java.awt.Dimension(250, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(txtSearchIdName, gridBagConstraints);

        cmbTimKiemLoaiKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả" }));
        cmbTimKiemLoaiKH.setMinimumSize(new java.awt.Dimension(100, 22));
        cmbTimKiemLoaiKH.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel2.add(cmbTimKiemLoaiKH, gridBagConstraints);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setMinimumSize(new java.awt.Dimension(100, 60));
        btnTimKiem.setPreferredSize(new java.awt.Dimension(100, 60));
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel2.add(btnTimKiem, gridBagConstraints);

        jLabel2.setText("Giới Tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(jLabel2, gridBagConstraints);

        cmbTimKiemGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả", "Nam", "Nữ" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel2.add(cmbTimKiemGioiTinh, gridBagConstraints);

        jLabel12.setText("Số điện thoại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(jLabel12, gridBagConstraints);

        txtTimKiemSDT.setMinimumSize(new java.awt.Dimension(250, 22));
        txtTimKiemSDT.setPreferredSize(new java.awt.Dimension(250, 22));
        txtTimKiemSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemSDTActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(txtTimKiemSDT, gridBagConstraints);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách khách hàng"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 402));

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 10);
        jPanel3.add(jScrollPane1, gridBagConstraints);

        btnResetTable.setText("Reset");
        btnResetTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetTableMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 10, 10);
        jPanel3.add(btnResetTable, gridBagConstraints);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        btnThem.setText("Thêm ");
        btnThem.setEnabled(false);
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btnThem, gridBagConstraints);

        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btnSua, gridBagConstraints);

        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btnXoa, gridBagConstraints);

        jPanel4.add(jPanel5);

        pnlKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm khách hàng"));
        pnlKhachHang.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlKhachHang.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Loại KH");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlKhachHang.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Họ Tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlKhachHang.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Điểm tích lũy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlKhachHang.add(jLabel7, gridBagConstraints);

        jLabel8.setText("SDT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlKhachHang.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlKhachHang.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Ngày sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlKhachHang.add(jLabel10, gridBagConstraints);

        txtIDKH.setEnabled(false);
        txtIDKH.setPreferredSize(new java.awt.Dimension(150, 22));
        txtIDKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDKHActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        pnlKhachHang.add(txtIDKH, gridBagConstraints);

        txtHoTen.setPreferredSize(new java.awt.Dimension(150, 22));
        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlKhachHang.add(txtHoTen, gridBagConstraints);

        txtSDT.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlKhachHang.add(txtSDT, gridBagConstraints);

        txtDiemTichLuy.setText("0");
        txtDiemTichLuy.setEnabled(false);
        txtDiemTichLuy.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlKhachHang.add(txtDiemTichLuy, gridBagConstraints);

        txtEmail.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlKhachHang.add(txtEmail, gridBagConstraints);

        cmbThemSuaLoaiKH.setEnabled(false);
        cmbThemSuaLoaiKH.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlKhachHang.add(cmbThemSuaLoaiKH, gridBagConstraints);

        btnReset.setText("Reset");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlKhachHang.add(btnReset, gridBagConstraints);

        btnLuu.setText("Lưu");
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlKhachHang.add(btnLuu, gridBagConstraints);

        jdcNgaySinh.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlKhachHang.add(jdcNgaySinh, gridBagConstraints);

        jLabel11.setText("Giới Tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlKhachHang.add(jLabel11, gridBagConstraints);

        cmbGioiTinhKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cmbGioiTinhKH.setPreferredSize(new java.awt.Dimension(150, 22));
        cmbGioiTinhKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGioiTinhKHActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlKhachHang.add(cmbGioiTinhKH, gridBagConstraints);

        jPanel4.add(pnlKhachHang);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng khác"));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        btnQLLKH.setText("Quản lý loại khách hàng");
        btnQLLKH.setMinimumSize(new java.awt.Dimension(180, 23));
        btnQLLKH.setPreferredSize(new java.awt.Dimension(180, 40));
        btnQLLKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLLKHMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel7.add(btnQLLKH, gridBagConstraints);

        btnImport.setText("Import");
        btnImport.setMinimumSize(new java.awt.Dimension(80, 40));
        btnImport.setPreferredSize(new java.awt.Dimension(80, 40));
        btnImport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImportMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel7.add(btnImport, gridBagConstraints);

        btnExport.setText("Export");
        btnExport.setMinimumSize(new java.awt.Dimension(80, 40));
        btnExport.setPreferredSize(new java.awt.Dimension(80, 40));
        btnExport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel7.add(btnExport, gridBagConstraints);

        jPanel4.add(jPanel7);
        jPanel4.add(filler1);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtIDKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKHActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:  
        int indexLoaiKH = cmbThemSuaLoaiKH.getSelectedIndex();
        int loaiKH = listLoaiKhach.get(indexLoaiKH).getId();
                   
        String hoTen = txtHoTen.getText().trim();
        if(hoTen.isBlank()){
            JOptionPane.showMessageDialog(this, "Họ tên không được để trống","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
        String sdt = txtSDT.getText().trim();
        if(!CheckHopLe.checkSoDienThoai(sdt)){
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int diemTichLuy = 0;
        
        Timestamp ngaySinh;
        ngaySinh = new Timestamp(jdcNgaySinh.getDate().getTime());
        int tuoi = Period.between(ngaySinh.toLocalDateTime().toLocalDate(), LocalDate.now()).getYears();
        if(tuoi < 18){
            JOptionPane.showMessageDialog(this, "Khách hàng phải từ 18 tuổi trở lên","Error", JOptionPane.ERROR_MESSAGE);
            return;            
        }
        
        boolean gioiTinhNam = true;
        if(cmbTimKiemGioiTinh.getSelectedIndex() == 1){
            gioiTinhNam = false;
        }        
        
        String email = txtEmail.getText().trim();
        if(!CheckHopLe.checkEmail(email)){
            JOptionPane.showMessageDialog(this, "Email không hợp lệ","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(dangThemKhachHang){
            CreateKhachHang_DTO data = new CreateKhachHang_DTO( hoTen, sdt, email, ngaySinh, gioiTinhNam);
            boolean result = khachHang_BUS.createKhachHang(data);
            if(result){
                JOptionPane.showMessageDialog(this, "Thêm khách hàng mới thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                clearThemSuaKhachHang();    
                loadTableKhachHang();
            }            
            else
                JOptionPane.showMessageDialog(this, "Thêm khách hàng mới thất bại","Error", JOptionPane.ERROR_MESSAGE);

        } else {
            int id = Integer.parseInt(txtIDKH.getText());
            
            UpdateKhachHang_DTO data = new UpdateKhachHang_DTO(id, loaiKH, hoTen, sdt, diemTichLuy, email, ngaySinh, gioiTinhNam);
            boolean result = khachHang_BUS.updateKhachHang(data);
            if(result){
                JOptionPane.showMessageDialog(this, "Sửa khách hàng thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadTableKhachHang();
            }            
            else
                JOptionPane.showMessageDialog(this, "Sửa khách hàng thất bại","Error", JOptionPane.ERROR_MESSAGE);
        }
        loadTableKhachHang();
    }//GEN-LAST:event_btnLuuMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        btnThem.setEnabled(true);
        btnSua.setEnabled(false);
        dangThemKhachHang = false;
        pnlKhachHang.setBorder(BorderFactory.createTitledBorder("Sửa khách hàng"));
        pnlKhachHang.repaint();
        clearThemSuaKhachHang();
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        if(dangThemKhachHang)
            clearThemSuaKhachHang();
        else {
            int id = Integer.parseInt(txtIDKH.getText());
            KhachHangFull_DTO result = khachHang_BUS.getKhachHangFullById(id);
        
            if(result == null){
                JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            txtHoTen.setText(result.getTen());
            txtSDT.setText(result.getSdt());
            txtDiemTichLuy.setText(Integer.toString(result.getDiemTichLuy()));
        }      
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        btnThem.setEnabled(false);
        btnSua.setEnabled(true);
        dangThemKhachHang = true;
        pnlKhachHang.setBorder(BorderFactory.createTitledBorder("Thêm khách hàng"));
        pnlKhachHang.repaint();
        clearThemSuaKhachHang();
    }//GEN-LAST:event_btnThemMouseClicked

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        // TODO add your handling code here:
        if(dangThemKhachHang)
            return;
        
        int index = tblKhachHang.getSelectedRow();
        TableModel model = tblKhachHang.getModel();
        
        int id = Integer.parseInt(model.getValueAt(index, 0).toString());
        KhachHangFull_DTO result = khachHang_BUS.getKhachHangFullById(id);
        
        if(result == null){
            JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        txtIDKH.setText(Integer.toString(result.getId()));
        txtHoTen.setText(result.getTen());
        txtSDT.setText(result.getSdt());
        txtDiemTichLuy.setText(Integer.toString(result.getDiemTichLuy()));
        txtEmail.setText(result.getEmail().trim());
        cmbThemSuaLoaiKH.setSelectedIndex(result.getLoaiKhachHang().getId()-1);
        jdcNgaySinh.setDate(result.getNgaySinh());
        if(result.isGioiTinhNam())
            cmbGioiTinhKH.setSelectedIndex(0);
        else
            cmbGioiTinhKH.setSelectedIndex(1);
        
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        int total = tblKhachHang.getSelectedRowCount();
        TableModel model = tblKhachHang.getModel();
        if(total < 1){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn khách hàng muốn xóa","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(null, 
                "Bạn có chắc chắn muốn xóa khách hàng đã chọn không ?", "Xóa dữ liệu khách hàng!", JOptionPane.OK_CANCEL_OPTION);
        
        if(confirm == JOptionPane.CANCEL_OPTION)
            return;
        
        if(total == 1){
            int index = tblKhachHang.getSelectedRow();

            int id = Integer.parseInt(model.getValueAt(index, 0).toString());

            boolean result = khachHang_BUS.deleteKhachHangById(id); 
            if(result){
                JOptionPane.showMessageDialog(this, "Xóa khách hàng thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                
            }            
            else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không được xóa nhiều khách hàng 1 thời điểm","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        clearThemSuaKhachHang();  
        loadTableKhachHang();
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnQLLKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLLKHMouseClicked
        // TODO add your handling code here:
        if(quanLyLoaiKhachHang_GUI == null || !quanLyLoaiKhachHang_GUI.isDisplayable()){
            quanLyLoaiKhachHang_GUI = new QuanLyLoaiKhachHang_GUI();
            quanLyLoaiKhachHang_GUI.setVisible(true);
        } else {
            quanLyLoaiKhachHang_GUI.setState(JFrame.NORMAL);
            quanLyLoaiKhachHang_GUI.toFront();
        }
    }//GEN-LAST:event_btnQLLKHMouseClicked

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
        // TODO add your handling code here:
        SearchKhachHang_DTO searchKhachHang_DTO = new SearchKhachHang_DTO();
        
        String idOrName = txtSearchIdName.getText();
        if(!idOrName.isBlank()){
            searchKhachHang_DTO.setIdOrName(idOrName.trim());
        }
        
        int idLoaiKhach = cmbTimKiemLoaiKH.getSelectedIndex();
        if(idLoaiKhach > 0){
            searchKhachHang_DTO.setLoaiKhachHang(listLoaiKhach.get(idLoaiKhach -1).getId());
        }
        
        int gioiTinh = cmbTimKiemGioiTinh.getSelectedIndex();
        switch (gioiTinh) {
            case 1 -> searchKhachHang_DTO.setGioiTinh(GioiTinhConstraints.NAM);
            case 2 -> searchKhachHang_DTO.setGioiTinh(GioiTinhConstraints.NU);
            default -> searchKhachHang_DTO.setGioiTinh(-1);       
        }
        
        String SDT = txtTimKiemSDT.getText().trim();
        if(!SDT.isBlank()){
            searchKhachHang_DTO.setSdt(SDT);
        }
         
        ArrayList<KhachHang_DTO> result = khachHang_BUS.searchKhachHang(searchKhachHang_DTO);
        loadTableKhachHang(result);
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void cmbGioiTinhKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGioiTinhKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGioiTinhKHActionPerformed

    private void txtTimKiemSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemSDTActionPerformed

    private void btnResetTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetTableMouseClicked
        // TODO add your handling code here:
        loadTableKhachHang();
        clearSearchBox();
    }//GEN-LAST:event_btnResetTableMouseClicked
    
    private void btnExportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportMouseClicked
        // TODO add your handling code here:
        TableModel model = tblKhachHang.getModel();
        ArrayList<String> listId = new ArrayList<>();
        int rowCount = model.getRowCount();
        boolean result = false;
        
        for(int i = 0; i < rowCount; i++){
            listId.add(model.getValueAt(i, 0).toString());
        }
        
        JFileChooser jFileChooser = new JFileChooser("D:");
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                
        if (jFileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            result = khachHang_BUS.exportKhachHang(listId, jFileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btnExportMouseClicked

    private void btnImportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportMouseClicked
        // TODO add your handling code here:
//        try {
            // Đọc dữ liệu từ tệp Excel
            
//
//                // Tạo DefaultTableModel từ dữ liệu đọc được
//                DefaultTableModel model = new DefaultTableModel();
//                Iterator<Row> rowIterator = sheet.iterator();
//                while (rowIterator.hasNext()) {
//                    Row row = rowIterator.next();
//                    Iterator<Cell> cellIterator = row.cellIterator();
//
//                    if (row.getRowNum() == 0) { // Header row
//                        while (cellIterator.hasNext()) {
//                            Cell cell = cellIterator.next();
//                            model.addColumn(cell.getStringCellValue());
//                        }
//                    } else { // Data rows
//                        Object[] rowData = new Object[model.getColumnCount()];
//                        int columnIndex = 0;
//                        while (cellIterator.hasNext()) {
//                            Cell cell = cellIterator.next();
//                            rowData[columnIndex++] = cell.getStringCellValue();
//                        }
//                        model.addRow(rowData);
//                    }
//                }
//                
//                tblKhachHang.setModel(model);
//                // Đóng workbook
//                workbook.close();

//            
//        } catch (IOException e) {
//            e.printStackTrace();
//        }

        try {
            JFileChooser jFileChooser = new JFileChooser("D:");
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();
            if (saveFile != null) {
                Workbook workbook = WorkbookFactory.create(new File(saveFile.toString()));
                Sheet sheet = workbook.getSheetAt(0);

                ArrayList<KhachHangFull_DTO> result = new ArrayList<>();
                    
                // Đọc dữ liệu từ các hàng trong sheet
                for (Row row : sheet) {
                    KhachHangFull_DTO khachHang = new KhachHangFull_DTO();
                    khachHang.setId((int) row.getCell(0).getNumericCellValue());
                    LoaiKhachHang_DAO lkh = new LoaiKhachHang_DAO();
                    khachHang.setLoaiKhachHang(lkh.getLoaiKhachHangById((int) row.getCell(1).getNumericCellValue()));
                    khachHang.setTen(row.getCell(2).getStringCellValue());
                    khachHang.setSdt(row.getCell(3).getStringCellValue());
                    khachHang.setDiemTichLuy((int) row.getCell(4).getNumericCellValue());
                    khachHang.setEmail(row.getCell(5).getStringCellValue());
                    Date date ;  
                    date = row.getCell(6).getDateCellValue();
                    Timestamp ngaySinh = new Timestamp(date.getTime());  
                    khachHang.setNgaySinh(ngaySinh);
                    khachHang.setGioiTinhNam(row.getCell(7).getBooleanCellValue());
                    
                    khachHang_BUS.importKhachHang(khachHang);
                }

                workbook.close();
                loadTableKhachHang();
            }else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnImportMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyKhachHang_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnQLLKH;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnResetTable;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cmbGioiTinhKH;
    private javax.swing.JComboBox<String> cmbThemSuaLoaiKH;
    private javax.swing.JComboBox<String> cmbTimKiemGioiTinh;
    private javax.swing.JComboBox<String> cmbTimKiemLoaiKH;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcNgaySinh;
    private javax.swing.JPanel pnlKhachHang;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtDiemTichLuy;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtIDKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSearchIdName;
    private javax.swing.JTextField txtTimKiemSDT;
    // End of variables declaration//GEN-END:variables

  
}
