/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.NhanVien_BUS;
import BUS.QuyenTaiKhoan_BUS;
import Constraints.ChucNangConstraints;
import DTO.NhanVien.NhanVienFull_DTO;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author tuant
 */
public class QuanLyQuyen_GUI extends javax.swing.JFrame {
    private final NhanVien_BUS nhanVien_BUS;
    private final NhanVienFull_DTO nhanVien;
    private final QuyenTaiKhoan_BUS quyenTaiKhoan_BUS;
    
    /**
     * Creates new form QuanLyQuyen
     * @param maNhanVien
     */
    public QuanLyQuyen_GUI(String maNhanVien) {
        initComponents();
        nhanVien_BUS = new NhanVien_BUS();
        nhanVien = nhanVien_BUS.getNhanVienbyMa(maNhanVien);
        quyenTaiKhoan_BUS = new QuyenTaiKhoan_BUS();
        
        txtMa.setText(maNhanVien);
        txtTen.setText(nhanVien.getHoTen());
        txtChucVu.setText(nhanVien.getChucVu().getTen());
        loadData();
    }

    public void loadData(){
        chkQuanLyPhucVu.setSelected(false);
        chkQuanLyBan.setSelected(false);
        chkQuanLyMonAn.setSelected(false);
        chkQuanLyHoaDon.setSelected(false);
        chkQuanLyNhanVien.setSelected(false);
        chkQuanLyKhachHang.setSelected(false);
        chkQuanLyTaiKhoan.setSelected(false);
        chkBaoCaoThongKe.setSelected(false);
        
        ArrayList<Integer> listChucNang = quyenTaiKhoan_BUS.getAllQuyenByMaNV(nhanVien.getMa());
        for(int chucNang : listChucNang){
            switch (chucNang) {
                case ChucNangConstraints.QUAN_LY_PHUC_VU -> chkQuanLyPhucVu.setSelected(true);
                case ChucNangConstraints.QUAN_LY_BAN -> chkQuanLyBan.setSelected(true);
                case ChucNangConstraints.QUAN_LY_MON_AN -> chkQuanLyMonAn.setSelected(true);
                case ChucNangConstraints.QUAN_LY_HOA_DON -> chkQuanLyHoaDon.setSelected(true);
                case ChucNangConstraints.QUAN_LY_NHAN_VIEN -> chkQuanLyNhanVien.setSelected(true);
                case ChucNangConstraints.QUAN_LY_KHACH_HANG -> chkQuanLyKhachHang.setSelected(true);
                case ChucNangConstraints.QUAN_LY_TAI_KHOAN -> chkQuanLyTaiKhoan.setSelected(true);
                case ChucNangConstraints.QUAN_LY_THONG_KE -> chkBaoCaoThongKe.setSelected(true);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlThemQuyenMoi = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblChucNang = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        chkQuanLyPhucVu = new javax.swing.JCheckBox();
        chkQuanLyBan = new javax.swing.JCheckBox();
        chkQuanLyMonAn = new javax.swing.JCheckBox();
        chkQuanLyHoaDon = new javax.swing.JCheckBox();
        chkQuanLyNhanVien = new javax.swing.JCheckBox();
        chkQuanLyKhachHang = new javax.swing.JCheckBox();
        chkQuanLyTaiKhoan = new javax.swing.JCheckBox();
        chkBaoCaoThongKe = new javax.swing.JCheckBox();
        lblID1 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        lblID2 = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý quyền");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlThemQuyenMoi.setMinimumSize(new java.awt.Dimension(320, 400));
        pnlThemQuyenMoi.setPreferredSize(new java.awt.Dimension(320, 400));
        pnlThemQuyenMoi.setLayout(new java.awt.GridBagLayout());

        lblID.setText("Mã nhân viên");
        lblID.setMaximumSize(new java.awt.Dimension(100, 16));
        lblID.setMinimumSize(new java.awt.Dimension(100, 16));
        lblID.setPreferredSize(new java.awt.Dimension(100, 16));
        pnlThemQuyenMoi.add(lblID, new java.awt.GridBagConstraints());

        lblChucNang.setText("Chức năng");
        lblChucNang.setMaximumSize(new java.awt.Dimension(60, 16));
        lblChucNang.setMinimumSize(new java.awt.Dimension(60, 16));
        lblChucNang.setPreferredSize(new java.awt.Dimension(60, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        pnlThemQuyenMoi.add(lblChucNang, gridBagConstraints);

        txtMa.setEnabled(false);
        txtMa.setMaximumSize(new java.awt.Dimension(172, 24));
        txtMa.setMinimumSize(new java.awt.Dimension(172, 24));
        txtMa.setPreferredSize(new java.awt.Dimension(172, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 22, 5, 0);
        pnlThemQuyenMoi.add(txtMa, gridBagConstraints);

        btnReset.setText("Reset");
        btnReset.setMaximumSize(new java.awt.Dimension(80, 24));
        btnReset.setMinimumSize(new java.awt.Dimension(80, 24));
        btnReset.setPreferredSize(new java.awt.Dimension(80, 24));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 5, 12);
        pnlThemQuyenMoi.add(btnReset, gridBagConstraints);

        btnLuu.setText("Lưu");
        btnLuu.setMaximumSize(new java.awt.Dimension(80, 24));
        btnLuu.setMinimumSize(new java.awt.Dimension(80, 24));
        btnLuu.setPreferredSize(new java.awt.Dimension(80, 24));
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 5, 12);
        pnlThemQuyenMoi.add(btnLuu, gridBagConstraints);

        chkQuanLyPhucVu.setText("Quản lý phục vụ");
        chkQuanLyPhucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkQuanLyPhucVuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyPhucVu, gridBagConstraints);

        chkQuanLyBan.setText("Quản lý bàn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyBan, gridBagConstraints);

        chkQuanLyMonAn.setText("Quản lý món ăn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyMonAn, gridBagConstraints);

        chkQuanLyHoaDon.setText("Quản lý hoá đơn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyHoaDon, gridBagConstraints);

        chkQuanLyNhanVien.setText("Quản lý nhân viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyNhanVien, gridBagConstraints);

        chkQuanLyKhachHang.setText("Quản lý khách hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyKhachHang, gridBagConstraints);

        chkQuanLyTaiKhoan.setText("Quản lý tài khoản");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyTaiKhoan, gridBagConstraints);

        chkBaoCaoThongKe.setText("Báo cáo thống kê");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkBaoCaoThongKe, gridBagConstraints);

        lblID1.setText("Tên nhân viên");
        lblID1.setMaximumSize(new java.awt.Dimension(100, 16));
        lblID1.setMinimumSize(new java.awt.Dimension(100, 16));
        lblID1.setPreferredSize(new java.awt.Dimension(100, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlThemQuyenMoi.add(lblID1, gridBagConstraints);

        txtTen.setEnabled(false);
        txtTen.setMaximumSize(new java.awt.Dimension(172, 24));
        txtTen.setMinimumSize(new java.awt.Dimension(172, 24));
        txtTen.setPreferredSize(new java.awt.Dimension(172, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 22, 5, 0);
        pnlThemQuyenMoi.add(txtTen, gridBagConstraints);

        lblID2.setText("Chức vụ");
        lblID2.setMaximumSize(new java.awt.Dimension(100, 16));
        lblID2.setMinimumSize(new java.awt.Dimension(100, 16));
        lblID2.setPreferredSize(new java.awt.Dimension(100, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlThemQuyenMoi.add(lblID2, gridBagConstraints);

        txtChucVu.setEnabled(false);
        txtChucVu.setMaximumSize(new java.awt.Dimension(172, 24));
        txtChucVu.setMinimumSize(new java.awt.Dimension(172, 24));
        txtChucVu.setPreferredSize(new java.awt.Dimension(172, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 22, 5, 0);
        pnlThemQuyenMoi.add(txtChucVu, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(pnlThemQuyenMoi, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkQuanLyPhucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkQuanLyPhucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkQuanLyPhucVuActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:
        Map<Integer, Boolean> map = new HashMap<>();
        map.put(ChucNangConstraints.QUAN_LY_PHUC_VU, chkQuanLyPhucVu.isSelected());
        map.put(ChucNangConstraints.QUAN_LY_BAN, chkQuanLyBan.isSelected());
        map.put(ChucNangConstraints.QUAN_LY_MON_AN, chkQuanLyMonAn.isSelected());
        map.put(ChucNangConstraints.QUAN_LY_HOA_DON, chkQuanLyHoaDon.isSelected());
        map.put(ChucNangConstraints.QUAN_LY_NHAN_VIEN, chkQuanLyNhanVien.isSelected());
        map.put(ChucNangConstraints.QUAN_LY_KHACH_HANG, chkQuanLyKhachHang.isSelected());
        map.put(ChucNangConstraints.QUAN_LY_TAI_KHOAN, chkQuanLyTaiKhoan.isSelected());
        map.put(ChucNangConstraints.QUAN_LY_THONG_KE, chkBaoCaoThongKe.isSelected());
        
        boolean result = quyenTaiKhoan_BUS.luu(nhanVien.getMa(), map);
        if(result){
            JOptionPane.showMessageDialog(this, "Sửa quyền thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }            
        else
            JOptionPane.showMessageDialog(this, "Sửa quyền thất bại","Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnLuuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyQuyen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyQuyen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyQuyen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyQuyen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyQuyen_GUI("quanla").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox chkBaoCaoThongKe;
    private javax.swing.JCheckBox chkQuanLyBan;
    private javax.swing.JCheckBox chkQuanLyHoaDon;
    private javax.swing.JCheckBox chkQuanLyKhachHang;
    private javax.swing.JCheckBox chkQuanLyMonAn;
    private javax.swing.JCheckBox chkQuanLyNhanVien;
    private javax.swing.JCheckBox chkQuanLyPhucVu;
    private javax.swing.JCheckBox chkQuanLyTaiKhoan;
    private javax.swing.JLabel lblChucNang;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblID2;
    private javax.swing.JPanel pnlThemQuyenMoi;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
