/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author tuant
 */
public class QuanLyTaiKhoan_GUI extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyHoaDon_GUI
     */
    public QuanLyTaiKhoan_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlDanhSachTaiKhoan = new javax.swing.JPanel();
        pnlBoLocTimKiem = new javax.swing.JPanel();
        lblNhapID = new javax.swing.JLabel();
        lblLocQuyen = new javax.swing.JLabel();
        txtNhapID = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnLocQuyen = new javax.swing.JButton();
        cmbChonQuyen = new javax.swing.JComboBox<>();
        pnlBangDanhSachTaiKhoan = new javax.swing.JPanel();
        scrDanhSachTaiKhoan = new javax.swing.JScrollPane();
        tblDanhSachTaiKhoan = new javax.swing.JTable();
        pnlChucNangTaiKhoan = new javax.swing.JPanel();
        pnlThemSua = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        pnlThemTaiKhoanMoi = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblQuyen = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        cmbQuyen = new javax.swing.JComboBox<>();
        btnTaoLai = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnlDanhSachTaiKhoan.setLayout(new javax.swing.BoxLayout(pnlDanhSachTaiKhoan, javax.swing.BoxLayout.Y_AXIS));

        pnlBoLocTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder("Bộ lọc tìm kiếm"));
        pnlBoLocTimKiem.setPreferredSize(new java.awt.Dimension(400, 100));
        pnlBoLocTimKiem.setLayout(new java.awt.GridBagLayout());

        lblNhapID.setText("Nhập ID");
        lblNhapID.setPreferredSize(new java.awt.Dimension(60, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 11);
        pnlBoLocTimKiem.add(lblNhapID, gridBagConstraints);

        lblLocQuyen.setText("Quyền");
        lblLocQuyen.setPreferredSize(new java.awt.Dimension(60, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlBoLocTimKiem.add(lblLocQuyen, gridBagConstraints);

        txtNhapID.setMaximumSize(new java.awt.Dimension(160, 24));
        txtNhapID.setMinimumSize(new java.awt.Dimension(160, 24));
        txtNhapID.setPreferredSize(new java.awt.Dimension(160, 24));
        txtNhapID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhapIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        pnlBoLocTimKiem.add(txtNhapID, gridBagConstraints);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setMaximumSize(new java.awt.Dimension(80, 24));
        btnTimKiem.setMinimumSize(new java.awt.Dimension(80, 24));
        btnTimKiem.setPreferredSize(new java.awt.Dimension(80, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        pnlBoLocTimKiem.add(btnTimKiem, gridBagConstraints);

        btnLocQuyen.setText("Lọc");
        btnLocQuyen.setMaximumSize(new java.awt.Dimension(80, 24));
        btnLocQuyen.setMinimumSize(new java.awt.Dimension(80, 24));
        btnLocQuyen.setPreferredSize(new java.awt.Dimension(80, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        pnlBoLocTimKiem.add(btnLocQuyen, gridBagConstraints);

        cmbChonQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbChonQuyen.setMaximumSize(new java.awt.Dimension(160, 24));
        cmbChonQuyen.setMinimumSize(new java.awt.Dimension(160, 24));
        cmbChonQuyen.setPreferredSize(new java.awt.Dimension(160, 24));
        cmbChonQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChonQuyenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        pnlBoLocTimKiem.add(cmbChonQuyen, gridBagConstraints);

        pnlDanhSachTaiKhoan.add(pnlBoLocTimKiem);

        pnlBangDanhSachTaiKhoan.setLayout(new java.awt.BorderLayout());

        scrDanhSachTaiKhoan.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách tài khoản"));
        scrDanhSachTaiKhoan.setPreferredSize(new java.awt.Dimension(200, 200));

        tblDanhSachTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Quyền", "Mật Khẩu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDanhSachTaiKhoan.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblDanhSachTaiKhoanAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        scrDanhSachTaiKhoan.setViewportView(tblDanhSachTaiKhoan);

        pnlBangDanhSachTaiKhoan.add(scrDanhSachTaiKhoan, java.awt.BorderLayout.CENTER);

        pnlDanhSachTaiKhoan.add(pnlBangDanhSachTaiKhoan);

        getContentPane().add(pnlDanhSachTaiKhoan);

        pnlChucNangTaiKhoan.setLayout(new javax.swing.BoxLayout(pnlChucNangTaiKhoan, javax.swing.BoxLayout.Y_AXIS));

        pnlThemSua.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));

        btnThem.setText("Thêm");
        btnThem.setMaximumSize(new java.awt.Dimension(80, 24));
        btnThem.setMinimumSize(new java.awt.Dimension(80, 24));
        btnThem.setPreferredSize(new java.awt.Dimension(80, 24));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlThemSua.add(btnThem);

        btnSua.setText("Sửa");
        btnSua.setMaximumSize(new java.awt.Dimension(80, 24));
        btnSua.setMinimumSize(new java.awt.Dimension(80, 24));
        btnSua.setPreferredSize(new java.awt.Dimension(80, 24));
        pnlThemSua.add(btnSua);

        pnlChucNangTaiKhoan.add(pnlThemSua);

        pnlThemTaiKhoanMoi.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm tài khoản"));
        pnlThemTaiKhoanMoi.setPreferredSize(new java.awt.Dimension(320, 220));
        pnlThemTaiKhoanMoi.setLayout(new java.awt.GridBagLayout());

        lblID.setText("ID");
        lblID.setMaximumSize(new java.awt.Dimension(60, 16));
        lblID.setMinimumSize(new java.awt.Dimension(60, 16));
        lblID.setPreferredSize(new java.awt.Dimension(60, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlThemTaiKhoanMoi.add(lblID, gridBagConstraints);

        lblQuyen.setText("Quyền");
        lblQuyen.setMaximumSize(new java.awt.Dimension(60, 16));
        lblQuyen.setMinimumSize(new java.awt.Dimension(60, 16));
        lblQuyen.setPreferredSize(new java.awt.Dimension(60, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlThemTaiKhoanMoi.add(lblQuyen, gridBagConstraints);

        lblMatKhau.setText("Mật khẩu");
        lblMatKhau.setMaximumSize(new java.awt.Dimension(60, 16));
        lblMatKhau.setMinimumSize(new java.awt.Dimension(60, 16));
        lblMatKhau.setPreferredSize(new java.awt.Dimension(60, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlThemTaiKhoanMoi.add(lblMatKhau, gridBagConstraints);

        txtID.setMaximumSize(new java.awt.Dimension(172, 24));
        txtID.setMinimumSize(new java.awt.Dimension(172, 24));
        txtID.setPreferredSize(new java.awt.Dimension(172, 24));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        pnlThemTaiKhoanMoi.add(txtID, gridBagConstraints);

        txtMatKhau.setMaximumSize(new java.awt.Dimension(172, 24));
        txtMatKhau.setMinimumSize(new java.awt.Dimension(172, 24));
        txtMatKhau.setPreferredSize(new java.awt.Dimension(172, 24));
        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        pnlThemTaiKhoanMoi.add(txtMatKhau, gridBagConstraints);

        cmbQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbQuyen.setMaximumSize(new java.awt.Dimension(172, 24));
        cmbQuyen.setMinimumSize(new java.awt.Dimension(172, 24));
        cmbQuyen.setPreferredSize(new java.awt.Dimension(172, 24));
        cmbQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbQuyenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        pnlThemTaiKhoanMoi.add(cmbQuyen, gridBagConstraints);

        btnTaoLai.setText("Tạo lại");
        btnTaoLai.setMaximumSize(new java.awt.Dimension(80, 24));
        btnTaoLai.setMinimumSize(new java.awt.Dimension(80, 24));
        btnTaoLai.setPreferredSize(new java.awt.Dimension(80, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 5, 12);
        pnlThemTaiKhoanMoi.add(btnTaoLai, gridBagConstraints);

        btnLuu.setText("Lưu");
        btnLuu.setMaximumSize(new java.awt.Dimension(80, 24));
        btnLuu.setMinimumSize(new java.awt.Dimension(80, 24));
        btnLuu.setPreferredSize(new java.awt.Dimension(80, 24));
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 5, 12);
        pnlThemTaiKhoanMoi.add(btnLuu, gridBagConstraints);

        pnlChucNangTaiKhoan.add(pnlThemTaiKhoanMoi);

        getContentPane().add(pnlChucNangTaiKhoan);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbChonQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChonQuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbChonQuyenActionPerformed

    private void txtNhapIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhapIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhapIDActionPerformed

    private void tblDanhSachTaiKhoanAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblDanhSachTaiKhoanAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDanhSachTaiKhoanAncestorAdded

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void cmbQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbQuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbQuyenActionPerformed

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyHoaDon_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLocQuyen;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaoLai;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cmbChonQuyen;
    private javax.swing.JComboBox<String> cmbQuyen;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLocQuyen;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblNhapID;
    private javax.swing.JLabel lblQuyen;
    private javax.swing.JPanel pnlBangDanhSachTaiKhoan;
    private javax.swing.JPanel pnlBoLocTimKiem;
    private javax.swing.JPanel pnlChucNangTaiKhoan;
    private javax.swing.JPanel pnlDanhSachTaiKhoan;
    private javax.swing.JPanel pnlThemSua;
    private javax.swing.JPanel pnlThemTaiKhoanMoi;
    private javax.swing.JScrollPane scrDanhSachTaiKhoan;
    private javax.swing.JTable tblDanhSachTaiKhoan;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNhapID;
    // End of variables declaration//GEN-END:variables
}
