/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.LoaiKhachHang_BUS;
import DTO.KhachHang.CreateLoaiKhachHang_DTO;
import DTO.KhachHang.LoaiKhachHang_DTO;
import DTO.KhachHang.UpdateLoaiKhachHang_DTO;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author tuant
 */
public class QuanLyLoaiKhachHang_GUI extends javax.swing.JFrame {
    private final LoaiKhachHang_BUS loaiKhachHang_BUS;
    private boolean dangThemLoaiKH = true;
    /**
     * Creates new form QuanLyLoaiKhachHang
     */
    public QuanLyLoaiKhachHang_GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        loaiKhachHang_BUS = new LoaiKhachHang_BUS();
        
        clearTextViewLoaiKH();
        loadTableKhachHang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLoaiKH = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        pnlLoaiKH = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtLoaiKH = new javax.swing.JTextField();
        txtDiemToiThieu = new javax.swing.JTextField();
        txtMucUuDai = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý loại khách hàng");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách loại khách hàng"));

        tblLoaiKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tên loại khách hàng", "Điểm tối thiểu", "Mức ưu đãi"
            }
        ));
        tblLoaiKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiKHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblLoaiKH);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        jPanel2.setMinimumSize(new java.awt.Dimension(80, 66));
        jPanel2.setPreferredSize(new java.awt.Dimension(80, 66));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnThem.setText("Thêm");
        btnThem.setEnabled(false);
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(btnThem, gridBagConstraints);

        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(btnSua, gridBagConstraints);

        jPanel4.add(jPanel2);

        pnlLoaiKH.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm loại khách hàng mới"));
        pnlLoaiKH.setLayout(new java.awt.GridBagLayout());

        jLabel7.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlLoaiKH.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Loại khách hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlLoaiKH.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Điểm tối thiểu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlLoaiKH.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Mức ưu đãi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlLoaiKH.add(jLabel10, gridBagConstraints);

        txtID.setEnabled(false);
        txtID.setMinimumSize(new java.awt.Dimension(250, 22));
        txtID.setPreferredSize(new java.awt.Dimension(250, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlLoaiKH.add(txtID, gridBagConstraints);

        txtLoaiKH.setMinimumSize(new java.awt.Dimension(250, 22));
        txtLoaiKH.setPreferredSize(new java.awt.Dimension(250, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlLoaiKH.add(txtLoaiKH, gridBagConstraints);

        txtDiemToiThieu.setPreferredSize(new java.awt.Dimension(70, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlLoaiKH.add(txtDiemToiThieu, gridBagConstraints);

        txtMucUuDai.setPreferredSize(new java.awt.Dimension(70, 22));
        txtMucUuDai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMucUuDaiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlLoaiKH.add(txtMucUuDai, gridBagConstraints);

        btnReset.setText("Reset");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlLoaiKH.add(btnReset, gridBagConstraints);

        btnLuu.setText("Lưu");
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlLoaiKH.add(btnLuu, gridBagConstraints);

        jPanel4.add(pnlLoaiKH);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void clearTextViewLoaiKH(){
        txtID.setText("");
        txtLoaiKH.setText("");
        txtDiemToiThieu.setText("");
        txtMucUuDai.setText("");
        
    }
    private void loadTableKhachHang(){
        ArrayList<LoaiKhachHang_DTO> listKhachHang = loaiKhachHang_BUS.getAllLoaiKhachHang();
        String col[] = {"ID", "Tên loại khách hàng", "Điểm tối thiểu ", "Mức ưu đãi "};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        tblLoaiKH.setModel(tableModel);
        for(LoaiKhachHang_DTO row : listKhachHang){
            Object[] data = {row.getId(), row.getTen(), row.getDiemToiThieu(), row.getMucUuDai()};
            tableModel.addRow(data);
        }
    }
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        btnThem.setEnabled(false);
        btnSua.setEnabled(true);
        dangThemLoaiKH = true;
        pnlLoaiKH.setBorder(BorderFactory.createTitledBorder("Thêm khách hàng"));
        pnlLoaiKH.repaint();
        clearTextViewLoaiKH();
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        btnThem.setEnabled(true);
        btnSua.setEnabled(false);
        dangThemLoaiKH = false;
        pnlLoaiKH.setBorder(BorderFactory.createTitledBorder("Sửa khách hàng"));
        pnlLoaiKH.repaint();
        clearTextViewLoaiKH();
    }//GEN-LAST:event_btnSuaMouseClicked

    private void txtMucUuDaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMucUuDaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMucUuDaiActionPerformed

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        if(dangThemLoaiKH)
            clearTextViewLoaiKH();
        else {
            int id = Integer.parseInt(txtID.getText());
            LoaiKhachHang_DTO result = loaiKhachHang_BUS.getLoaiKhachHangById(id);
        
            if(result == null){
                JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            txtLoaiKH.setText(result.getTen());
            txtDiemToiThieu.setText(Integer.toString(result.getDiemToiThieu()));
            txtMucUuDai.setText(Double.toString(result.getMucUuDai()));
            
        }
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:
        String loaiKH = txtLoaiKH.getText().trim();
        if(loaiKH.isBlank())
            JOptionPane.showMessageDialog(this, "Loại khách hàng không được để trống","Error", JOptionPane.ERROR_MESSAGE);
            
        int diemToiThieu;
        try{            
            diemToiThieu = Integer.parseInt(txtDiemToiThieu.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Nhập sai định dạng điểm tối thiểu ","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double mucUuDai;
        try{            
            mucUuDai = Double.parseDouble(txtMucUuDai.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Nhập sai định dạng mức ưu đãi ","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(dangThemLoaiKH){
            CreateLoaiKhachHang_DTO data = new CreateLoaiKhachHang_DTO(loaiKH, diemToiThieu,mucUuDai);

            boolean result = loaiKhachHang_BUS.createLoaiKhachHang(data);
            if(result){
                JOptionPane.showMessageDialog(this, "Thêm loại khách hàng mới thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                clearTextViewLoaiKH();            
            }            
            else
                JOptionPane.showMessageDialog(this, "Thêm loại khách hàng mới thất bại","Error", JOptionPane.ERROR_MESSAGE);

        } else {
            int id = Integer.parseInt(txtID.getText());
            
            UpdateLoaiKhachHang_DTO data = new UpdateLoaiKhachHang_DTO(id,loaiKH, diemToiThieu,mucUuDai);
            Boolean result = loaiKhachHang_BUS.updateLoaiKhachHang(data);
            if(result){
                JOptionPane.showMessageDialog(this, "Sửa loại khách hàng thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                clearTextViewLoaiKH();            
            }            
            else
                JOptionPane.showMessageDialog(this, "Sửa loại khách hàng thất bại","Error", JOptionPane.ERROR_MESSAGE);
        }
        loadTableKhachHang();
    }//GEN-LAST:event_btnLuuMouseClicked

    private void tblLoaiKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiKHMouseClicked
        // TODO add your handling code here:
        if(dangThemLoaiKH)
            return;
        
        int index = tblLoaiKH.getSelectedRow();
        TableModel model = tblLoaiKH.getModel();
        
        int id = Integer.parseInt(model.getValueAt(index, 0).toString());
        LoaiKhachHang_DTO result = loaiKhachHang_BUS.getLoaiKhachHangById(id);
        
        if(result == null){
            JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        txtID.setText(Integer.toString(result.getId()));
        txtLoaiKH.setText(result.getTen());
        txtDiemToiThieu.setText(Integer.toString(result.getDiemToiThieu()));
        txtMucUuDai.setText(Double.toString(result.getMucUuDai()));
    }//GEN-LAST:event_tblLoaiKHMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiKhachHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiKhachHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiKhachHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiKhachHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyLoaiKhachHang_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlLoaiKH;
    private javax.swing.JTable tblLoaiKH;
    private javax.swing.JTextField txtDiemToiThieu;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLoaiKH;
    private javax.swing.JTextField txtMucUuDai;
    // End of variables declaration//GEN-END:variables
}
