/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author tuant
 */
public class QuanLyQuyen_GUI extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyQuyen
     */
    public QuanLyQuyen_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlDanhSachQuyen = new javax.swing.JPanel();
        scrDanhSachTaiKhoan = new javax.swing.JScrollPane();
        tblDanhSachTaiKhoan = new javax.swing.JTable();
        pnlChucNang = new javax.swing.JPanel();
        pnlThemSua = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        pnlThemQuyenMoi = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblQuyen = new javax.swing.JLabel();
        lblChucNang = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtQuyen = new javax.swing.JTextField();
        btnTaoLai = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        chkQuanLyPhucVu = new javax.swing.JCheckBox();
        chkQuanLyLoaiBan = new javax.swing.JCheckBox();
        chkQuanLyMonAn = new javax.swing.JCheckBox();
        chkQuanLyHoaDon = new javax.swing.JCheckBox();
        chkQuanLyNhanVien = new javax.swing.JCheckBox();
        chkQuanLyKhachHang = new javax.swing.JCheckBox();
        chkQuanLyTaiKhoan = new javax.swing.JCheckBox();
        chkBaoCaoThongKe = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnlDanhSachQuyen.setLayout(new javax.swing.BoxLayout(pnlDanhSachQuyen, javax.swing.BoxLayout.Y_AXIS));

        scrDanhSachTaiKhoan.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách quyền"));
        scrDanhSachTaiKhoan.setPreferredSize(new java.awt.Dimension(200, 200));

        tblDanhSachTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Quyền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDanhSachTaiKhoan.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblDanhSachTaiKhoanAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        scrDanhSachTaiKhoan.setViewportView(tblDanhSachTaiKhoan);

        pnlDanhSachQuyen.add(scrDanhSachTaiKhoan);

        getContentPane().add(pnlDanhSachQuyen);

        pnlChucNang.setLayout(new javax.swing.BoxLayout(pnlChucNang, javax.swing.BoxLayout.Y_AXIS));

        pnlThemSua.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        pnlThemSua.setMinimumSize(new java.awt.Dimension(200, 60));
        pnlThemSua.setPreferredSize(new java.awt.Dimension(200, 60));

        btnThem.setText("Thêm");
        btnThem.setMaximumSize(new java.awt.Dimension(80, 24));
        btnThem.setMinimumSize(new java.awt.Dimension(80, 24));
        btnThem.setPreferredSize(new java.awt.Dimension(80, 24));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlThemSua.add(btnThem);

        btnSua.setText("Sửa");
        btnSua.setMaximumSize(new java.awt.Dimension(80, 24));
        btnSua.setMinimumSize(new java.awt.Dimension(80, 24));
        btnSua.setPreferredSize(new java.awt.Dimension(80, 24));
        pnlThemSua.add(btnSua);

        pnlChucNang.add(pnlThemSua);

        pnlThemQuyenMoi.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm quyền mới"));
        pnlThemQuyenMoi.setMinimumSize(new java.awt.Dimension(320, 440));
        pnlThemQuyenMoi.setPreferredSize(new java.awt.Dimension(320, 440));
        pnlThemQuyenMoi.setLayout(new java.awt.GridBagLayout());

        lblID.setText("ID");
        lblID.setMaximumSize(new java.awt.Dimension(60, 16));
        lblID.setMinimumSize(new java.awt.Dimension(60, 16));
        lblID.setPreferredSize(new java.awt.Dimension(60, 16));
        pnlThemQuyenMoi.add(lblID, new java.awt.GridBagConstraints());

        lblQuyen.setText("Quyền");
        lblQuyen.setMaximumSize(new java.awt.Dimension(60, 16));
        lblQuyen.setMinimumSize(new java.awt.Dimension(60, 16));
        lblQuyen.setPreferredSize(new java.awt.Dimension(60, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        pnlThemQuyenMoi.add(lblQuyen, gridBagConstraints);

        lblChucNang.setText("Chức năng");
        lblChucNang.setMaximumSize(new java.awt.Dimension(60, 16));
        lblChucNang.setMinimumSize(new java.awt.Dimension(60, 16));
        lblChucNang.setPreferredSize(new java.awt.Dimension(60, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 10);
        pnlThemQuyenMoi.add(lblChucNang, gridBagConstraints);

        txtID.setMaximumSize(new java.awt.Dimension(172, 24));
        txtID.setMinimumSize(new java.awt.Dimension(172, 24));
        txtID.setPreferredSize(new java.awt.Dimension(172, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 22, 5, 0);
        pnlThemQuyenMoi.add(txtID, gridBagConstraints);

        txtQuyen.setMaximumSize(new java.awt.Dimension(172, 24));
        txtQuyen.setMinimumSize(new java.awt.Dimension(172, 24));
        txtQuyen.setPreferredSize(new java.awt.Dimension(172, 24));
        txtQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuyenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 22, 0, 0);
        pnlThemQuyenMoi.add(txtQuyen, gridBagConstraints);

        btnTaoLai.setText("Tạo lại");
        btnTaoLai.setMaximumSize(new java.awt.Dimension(80, 24));
        btnTaoLai.setMinimumSize(new java.awt.Dimension(80, 24));
        btnTaoLai.setPreferredSize(new java.awt.Dimension(80, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 5, 12);
        pnlThemQuyenMoi.add(btnTaoLai, gridBagConstraints);

        btnLuu.setText("Lưu");
        btnLuu.setMaximumSize(new java.awt.Dimension(80, 24));
        btnLuu.setMinimumSize(new java.awt.Dimension(80, 24));
        btnLuu.setPreferredSize(new java.awt.Dimension(80, 24));
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 5, 12);
        pnlThemQuyenMoi.add(btnLuu, gridBagConstraints);

        chkQuanLyPhucVu.setText("Quản lý phục vụ");
        chkQuanLyPhucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkQuanLyPhucVuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyPhucVu, gridBagConstraints);

        chkQuanLyLoaiBan.setText("Quản lý loại bàn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyLoaiBan, gridBagConstraints);

        chkQuanLyMonAn.setText("Quản lý món ăn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyMonAn, gridBagConstraints);

        chkQuanLyHoaDon.setText("Quản lý hoá đơn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyHoaDon, gridBagConstraints);

        chkQuanLyNhanVien.setText("Quản lý nhân viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyNhanVien, gridBagConstraints);

        chkQuanLyKhachHang.setText("Quản lý khách hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyKhachHang, gridBagConstraints);

        chkQuanLyTaiKhoan.setText("Quản lý tài khoản");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkQuanLyTaiKhoan, gridBagConstraints);

        chkBaoCaoThongKe.setText("Báo cáo thống kê");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 6, 0);
        pnlThemQuyenMoi.add(chkBaoCaoThongKe, gridBagConstraints);

        pnlChucNang.add(pnlThemQuyenMoi);

        getContentPane().add(pnlChucNang);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhSachTaiKhoanAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblDanhSachTaiKhoanAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDanhSachTaiKhoanAncestorAdded

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuyenActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuActionPerformed

    private void chkQuanLyPhucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkQuanLyPhucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkQuanLyPhucVuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyQuyen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyQuyen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyQuyen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyQuyen_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyQuyen_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaoLai;
    private javax.swing.JButton btnThem;
    private javax.swing.JCheckBox chkBaoCaoThongKe;
    private javax.swing.JCheckBox chkQuanLyHoaDon;
    private javax.swing.JCheckBox chkQuanLyKhachHang;
    private javax.swing.JCheckBox chkQuanLyLoaiBan;
    private javax.swing.JCheckBox chkQuanLyMonAn;
    private javax.swing.JCheckBox chkQuanLyNhanVien;
    private javax.swing.JCheckBox chkQuanLyPhucVu;
    private javax.swing.JCheckBox chkQuanLyTaiKhoan;
    private javax.swing.JLabel lblChucNang;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblQuyen;
    private javax.swing.JPanel pnlChucNang;
    private javax.swing.JPanel pnlDanhSachQuyen;
    private javax.swing.JPanel pnlThemQuyenMoi;
    private javax.swing.JPanel pnlThemSua;
    private javax.swing.JScrollPane scrDanhSachTaiKhoan;
    private javax.swing.JTable tblDanhSachTaiKhoan;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtQuyen;
    // End of variables declaration//GEN-END:variables
}
