/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.KhachHang_BUS;
import BUS.LoaiKhachHang_BUS;
import DTO.KhachHang.CreateKhachHang_DTO;
import DTO.KhachHang.KhachHangFull_DTO;
import DTO.KhachHang.KhachHang_DTO;
import DTO.KhachHang.LoaiKhachHang_DTO;
import DTO.KhachHang.UpdateKhachHang_DTO;
import java.sql.Timestamp;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author tuant
 */
public class QuanLyKhachHang_GUI extends javax.swing.JFrame {
    private final LoaiKhachHang_BUS loaiKhach_BUS;
    private final KhachHang_BUS khachHang_BUS;
    private boolean dangThemKhachHang = true;
    
    private QuanLyLoaiKhachHang_GUI quanLyLoaiKhachHang_GUI;
    
    private ArrayList<LoaiKhachHang_DTO> listLoaiKhach;
    /**
     * Creates new form QuanLyKhachHang_GUI
     */
    public QuanLyKhachHang_GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        khachHang_BUS = new KhachHang_BUS();
        loaiKhach_BUS = new LoaiKhachHang_BUS();
        
        loadTableKhachHang();
        loadComboBoxLoaiKhach();
        loadComboBoxLoaiKH();
        clearTextViewKhachHang();
        
    }
    private void loadTableKhachHang(){
        ArrayList<KhachHang_DTO> listKhachHang = khachHang_BUS.getAllKhachHang();
        String col[] = {"ID", "Tên khách hàng", "Số diện thoại ", "Điểm tích lũy ", "Loại khách hàng "};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        tblKhachHang.setModel(tableModel);
        for(KhachHang_DTO row : listKhachHang){
            Object[] data = {row.getId(), row.getTen(), row.getSdt(), row.getDiemTichLuy(), row.getLoaiKhachHang().getTen()};
            tableModel.addRow(data);
        }
    }
    
    private void loadComboBoxLoaiKhach(){
        listLoaiKhach = loaiKhach_BUS.getAllLoaiKhachHang();        
        
        for(LoaiKhachHang_DTO loaiBan : listLoaiKhach){
            cmbLoaiKhach.addItem(loaiBan.getTen());
        }      
        
        cmbLoaiKhach.setSelectedIndex(-1);
    }
    private void loadComboBoxLoaiKH(){
        listLoaiKhach = loaiKhach_BUS.getAllLoaiKhachHang();        
        
        for(LoaiKhachHang_DTO loaiBan : listLoaiKhach){
            cmbLoaiKH.addItem(loaiBan.getTen());
        }      
        
        cmbLoaiKH.setSelectedIndex(-1);
    }
    
    private void clearTextViewKhachHang(){
        txtID.setText("");
        txtMaKH.setText("");
        txtHoTen.setText("");
        txtSDT.setText("");
        txtDiemTichLuy.setText("");
        txtEmail.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        cmbGioiTinh = new javax.swing.JComboBox<>();
        cmbLoaiKhach = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        pnlKhachHang = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiemTichLuy = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cmbLoaiKH = new javax.swing.JComboBox<>();
        btnReset = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jdcNgaySinh = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        btnQuanLyLoaiKhachHang = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 200), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý khách hàng");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bộ lọc danh sách khách hàng"));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 120));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nhập ID hoặc tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Giới tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Loại khách");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jLabel3, gridBagConstraints);

        txtID.setMinimumSize(new java.awt.Dimension(200, 22));
        txtID.setPreferredSize(new java.awt.Dimension(250, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(txtID, gridBagConstraints);

        cmbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAM", "NỮ" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(cmbGioiTinh, gridBagConstraints);

        cmbLoaiKhach.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel2.add(cmbLoaiKhach, gridBagConstraints);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setMinimumSize(new java.awt.Dimension(100, 60));
        btnTimKiem.setPreferredSize(new java.awt.Dimension(100, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel2.add(btnTimKiem, gridBagConstraints);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách khách hàng"));

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng"));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        btnThem.setText("Thêm ");
        btnThem.setEnabled(false);
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btnThem, gridBagConstraints);

        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btnSua, gridBagConstraints);

        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel5.add(btnXoa, gridBagConstraints);

        jPanel4.add(jPanel5);

        pnlKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm khách hàng"));
        pnlKhachHang.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Mã KH");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        pnlKhachHang.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Loại KH");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlKhachHang.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Họ Tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlKhachHang.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Điểm tích lũy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlKhachHang.add(jLabel7, gridBagConstraints);

        jLabel8.setText("SDT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlKhachHang.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlKhachHang.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Ngày sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlKhachHang.add(jLabel10, gridBagConstraints);

        txtMaKH.setEnabled(false);
        txtMaKH.setPreferredSize(new java.awt.Dimension(150, 22));
        txtMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKHActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        pnlKhachHang.add(txtMaKH, gridBagConstraints);

        txtHoTen.setPreferredSize(new java.awt.Dimension(150, 22));
        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlKhachHang.add(txtHoTen, gridBagConstraints);

        txtSDT.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlKhachHang.add(txtSDT, gridBagConstraints);

        txtDiemTichLuy.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlKhachHang.add(txtDiemTichLuy, gridBagConstraints);

        txtEmail.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlKhachHang.add(txtEmail, gridBagConstraints);

        cmbLoaiKH.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlKhachHang.add(cmbLoaiKH, gridBagConstraints);

        btnReset.setText("Reset");
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlKhachHang.add(btnReset, gridBagConstraints);

        btnLuu.setText("Lưu");
        btnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLuuMouseClicked(evt);
            }
        });
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        pnlKhachHang.add(btnLuu, gridBagConstraints);

        jdcNgaySinh.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        pnlKhachHang.add(jdcNgaySinh, gridBagConstraints);

        jPanel4.add(pnlKhachHang);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức năng khác"));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        btnQuanLyLoaiKhachHang.setText("Quản lý loại khách hàng");
        btnQuanLyLoaiKhachHang.setMinimumSize(new java.awt.Dimension(180, 23));
        btnQuanLyLoaiKhachHang.setPreferredSize(new java.awt.Dimension(180, 40));
        btnQuanLyLoaiKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyLoaiKhachHangMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel7.add(btnQuanLyLoaiKhachHang, gridBagConstraints);

        btnImport.setText("Import");
        btnImport.setMinimumSize(new java.awt.Dimension(80, 40));
        btnImport.setPreferredSize(new java.awt.Dimension(80, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanel7.add(btnImport, gridBagConstraints);

        btnExport.setText("Export");
        btnExport.setMinimumSize(new java.awt.Dimension(80, 40));
        btnExport.setPreferredSize(new java.awt.Dimension(80, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel7.add(btnExport, gridBagConstraints);

        jPanel4.add(jPanel7);
        jPanel4.add(filler1);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKHActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnLuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLuuMouseClicked
        // TODO add your handling code here:        
        int loaiKH = cmbLoaiKH.getSelectedIndex();
        if(loaiKH == -1){
            JOptionPane.showMessageDialog(this, "Họ tên không được để trống","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
                   
        String hoTen = txtHoTen.getText().trim();
        if(hoTen.isBlank()){
            JOptionPane.showMessageDialog(this, "Họ tên không được để trống","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
        String sdt = txtSDT.getText().trim();
        if(sdt.isBlank()){
            JOptionPane.showMessageDialog(this, "Số điện thoại không được để trống","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int diemTichLuy;
        try{            
            diemTichLuy = Integer.parseInt(txtDiemTichLuy.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Nhập sai định dạng điểm tích lũy ","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(diemTichLuy <= 0){
            JOptionPane.showMessageDialog(this, "Điểm tích lũy phải lớn hơn 0","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String email = txtEmail.getText().trim();
        if(email.isBlank()){
            JOptionPane.showMessageDialog(this, "Email không được để trống","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Timestamp ngaySinh;
        ngaySinh = new Timestamp(jdcNgaySinh.getDate().getTime());
        
        if(dangThemKhachHang){
            CreateKhachHang_DTO data = new CreateKhachHang_DTO(loaiKH,hoTen,sdt,diemTichLuy,email,ngaySinh);

            boolean result = khachHang_BUS.createKhachHang(data);
            if(result){
                JOptionPane.showMessageDialog(this, "Thêm khách hàng mới thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                clearTextViewKhachHang();            
            }            
            else
                JOptionPane.showMessageDialog(this, "Thêm khách hàng mới thất bại","Error", JOptionPane.ERROR_MESSAGE);

        } else {
            int id = Integer.parseInt(txtMaKH.getText());
            
            UpdateKhachHang_DTO data = new UpdateKhachHang_DTO(id,loaiKH, hoTen,sdt,diemTichLuy,email,ngaySinh);
            Boolean result = khachHang_BUS.updateKhachHang(data);
            if(result){
                JOptionPane.showMessageDialog(this, "Sửa khách hàng thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                clearTextViewKhachHang();            
            }            
            else
                JOptionPane.showMessageDialog(this, "Sửa khách hàng thất bại","Error", JOptionPane.ERROR_MESSAGE);
        }
        loadTableKhachHang();
    }//GEN-LAST:event_btnLuuMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        btnThem.setEnabled(true);
        btnSua.setEnabled(false);
        dangThemKhachHang = false;
        pnlKhachHang.setBorder(BorderFactory.createTitledBorder("Sửa khách hàng"));
        pnlKhachHang.repaint();
        clearTextViewKhachHang();
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        if(dangThemKhachHang)
            clearTextViewKhachHang();
        else {
            int id = Integer.parseInt(txtMaKH.getText());
            KhachHangFull_DTO result = khachHang_BUS.getKhachHangFullById(id);
        
            if(result == null){
                JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            txtHoTen.setText(result.getTen());
            txtSDT.setText(result.getSdt());
            txtDiemTichLuy.setText(Integer.toString(result.getDiemTichLuy()));
            
        }      
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        btnThem.setEnabled(false);
        btnSua.setEnabled(true);
        dangThemKhachHang = true;
        pnlKhachHang.setBorder(BorderFactory.createTitledBorder("Thêm khách hàng"));
        pnlKhachHang.repaint();
        clearTextViewKhachHang();
    }//GEN-LAST:event_btnThemMouseClicked

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        // TODO add your handling code here:
        if(dangThemKhachHang)
            return;
        
        int index = tblKhachHang.getSelectedRow();
        TableModel model = tblKhachHang.getModel();
        
        int id = Integer.parseInt(model.getValueAt(index, 0).toString());
        KhachHangFull_DTO result = khachHang_BUS.getKhachHangFullById(id);
        
        if(result == null){
            JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        txtID.setText(Integer.toString(result.getId()));
        txtHoTen.setText(result.getTen());
        txtSDT.setText(result.getSdt());
        txtDiemTichLuy.setText(Integer.toString(result.getDiemTichLuy()));
        txtEmail.setText(result.getEmail());
        
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        int total = tblKhachHang.getSelectedRowCount();
        TableModel model = tblKhachHang.getModel();
        if(total < 1){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn loại bàn muốn xóa","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(null, 
                "Bạn có chắc chắn muốn xóa " + total + " loại bàn không ?", "Xóa dữ liệu loại bàn!", JOptionPane.OK_CANCEL_OPTION);
        
        if(confirm == JOptionPane.CANCEL_OPTION)
            return;
        
        if(total == 1){
            int index = tblKhachHang.getSelectedRow();

            int id = Integer.parseInt(model.getValueAt(index, 0).toString());

            boolean result = khachHang_BUS.deleteKhachHangById(id); 
            if(result){
                JOptionPane.showMessageDialog(this, "Xóa 1 loại bàn thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);
                
            }            
            else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            }
        clearTextViewKhachHang();  
        loadTableKhachHang();
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnQuanLyLoaiKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyLoaiKhachHangMouseClicked
        // TODO add your handling code here:
        
        if(quanLyLoaiKhachHang_GUI == null || !quanLyLoaiKhachHang_GUI.isDisplayable()){
            quanLyLoaiKhachHang_GUI = new QuanLyLoaiKhachHang_GUI();
            quanLyLoaiKhachHang_GUI.setVisible(true);
        } else {
            quanLyLoaiKhachHang_GUI.setState(JFrame.NORMAL);
            quanLyLoaiKhachHang_GUI.toFront();
        }
    }//GEN-LAST:event_btnQuanLyLoaiKhachHangMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyKhachHang_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnQuanLyLoaiKhachHang;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cmbGioiTinh;
    private javax.swing.JComboBox<String> cmbLoaiKH;
    private javax.swing.JComboBox<String> cmbLoaiKhach;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcNgaySinh;
    private javax.swing.JPanel pnlKhachHang;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtDiemTichLuy;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
