package GUI;

import BUS.Ban_BUS;
import BUS.DonGoi_BUS;
import BUS.HoaDon_BUS;
import BUS.KhachHang_BUS;
import BUS.NhanVien_BUS;
import Constraints.TinhTrangBanConstraints;
import DTO.Ban.DonGoi_DTO;
import DTO.HoaDon.ChiTietHoaDon_DTO;
import DTO.HoaDon.CreateChiTietHoaDon_DTO;
import DTO.HoaDon.CreateHoaDon_DTO;
import DTO.KhachHang.KhachHangFull_DTO;
import DTO.KhachHang.UpdateKhachHang_DTO;
import DTO.NhanVien.NhanVienFull_DTO;
import com.mycompany.quanlynhahang.CheckHopLe;
import com.mycompany.quanlynhahang.Price;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuant
 */
public class ThanhToan_GUI extends javax.swing.JFrame {
    private int idBan;
    private DonGoi_BUS donGoi_BUS;
    private KhachHang_BUS khachHang_BUS;
    private HoaDon_BUS hoaDon_BUS;
    private int tongTien;
    private ArrayList<DonGoi_DTO> listDonGoi;
    private String maNhanVien;
    private NhanVien_BUS nhanVien_BUS;
    private KhachHangFull_DTO khachHang;
    private Ban_BUS ban_BUS;
    int total = 0;
    /**
     * Creates new form HoaDon_GUI
     */
    public ThanhToan_GUI(int idBan, String maNhanVien) {
        initComponents();
        this.idBan = idBan;
        donGoi_BUS = new DonGoi_BUS();
        khachHang_BUS = new KhachHang_BUS();
        nhanVien_BUS = new NhanVien_BUS();
        hoaDon_BUS = new HoaDon_BUS();
        this.maNhanVien = maNhanVien;
        KhachHangFull_DTO khachHang;
        ban_BUS = new Ban_BUS();
        
        loadThanhToan();
        loadDonGoi();
    }
    
    private void loadThanhToan(){
        lblTitleBan.setText("Bàn số " + idBan);
        
        NhanVienFull_DTO nhanVienFull_DTO = nhanVien_BUS.getNhanVienbyMa(maNhanVien);
        lblNhanVien.setText("Nhân viên lập hóa đơn: " + nhanVienFull_DTO.getHoTen());
    }
    
    private void loadDonGoi(){
        listDonGoi = donGoi_BUS.getAllDonGoiByIdBan(idBan);
        
        String[] col = {"ID Món ăn", "Tên món ăn", "Đơn giá", "Số lượng", "Thành tiền"};
        DefaultTableModel model = new DefaultTableModel(col, 0);
        tblDonGoi.setModel(model);
        
        for(DonGoi_DTO donGoi : listDonGoi){
            int gia = donGoi.getMonAn().getGiaKhuyenMai() > 0 ?
                    donGoi.getMonAn().getGiaKhuyenMai() :
                    donGoi.getMonAn().getGia();
            int tongTien = gia * donGoi.getSoLuong();
            total += tongTien;
            
            Object[] data = {
                donGoi.getMonAn().getId(), 
                donGoi.getMonAn().getTen(),
                Price.formatPrice(tongTien),
                donGoi.getSoLuong(),
                Price.formatPrice(tongTien)
                };
            model.addRow(data);
        }
        
        tongTien = total;
        lblTongTien.setText(Price.formatPrice(tongTien));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblNhanVien = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSDTKhachHang = new javax.swing.JTextField();
        btnTimKhachHang = new javax.swing.JButton();
        lblTitleBan = new javax.swing.JLabel();
        lblTenKhachHang = new javax.swing.JLabel();
        lblSDTKhachHang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonGoi = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTongThanhToan = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblMucUuDai = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        btnInBillTam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thanh toán");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblNhanVien.setText("Nhân viên lập hóa đơn: Phan Hoàng Nhật Tân");
        lblNhanVien.setMaximumSize(new java.awt.Dimension(300, 16));
        lblNhanVien.setMinimumSize(new java.awt.Dimension(300, 16));
        lblNhanVien.setPreferredSize(new java.awt.Dimension(300, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(lblNhanVien, gridBagConstraints);

        jLabel9.setText("Tìm khách hàng theo số điện thoại:");
        jLabel9.setMaximumSize(new java.awt.Dimension(192, 16));
        jLabel9.setMinimumSize(new java.awt.Dimension(192, 16));
        jLabel9.setPreferredSize(new java.awt.Dimension(192, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel1.add(jLabel9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtSDTKhachHang, gridBagConstraints);

        btnTimKhachHang.setText("Tìm kiếm");
        btnTimKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKhachHangMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        jPanel1.add(btnTimKhachHang, gridBagConstraints);

        lblTitleBan.setText("Bàn số 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel1.add(lblTitleBan, gridBagConstraints);

        lblTenKhachHang.setText("Tên khách hàng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(lblTenKhachHang, gridBagConstraints);

        lblSDTKhachHang.setText("Số điện thoại:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(lblSDTKhachHang, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 5, 20);
        getContentPane().add(jPanel1, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(452, 206));

        tblDonGoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Món ăn", "Tên món ăn", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ));
        tblDonGoi.setMinimumSize(new java.awt.Dimension(300, 80));
        tblDonGoi.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(tblDonGoi);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 20);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Tổng tiền");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 8, 0, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        lblTongThanhToan.setText("0 VNĐ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 8);
        jPanel2.add(lblTongThanhToan, gridBagConstraints);

        lblTongTien.setText("0 VNĐ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 8);
        jPanel2.add(lblTongTien, gridBagConstraints);

        jLabel5.setText("Ưu đãi thành viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 8, 0, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Tổng thanh toán");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 8, 0, 0);
        jPanel2.add(jLabel6, gridBagConstraints);

        lblMucUuDai.setText("0 %");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 8);
        jPanel2.add(lblMucUuDai, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 20);
        getContentPane().add(jPanel2, gridBagConstraints);

        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThanhToanMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 10, 20);
        getContentPane().add(btnThanhToan, gridBagConstraints);

        btnInBillTam.setText("In bill tạm");
        btnInBillTam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInBillTamMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 10, 20);
        getContentPane().add(btnInBillTam, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKhachHangMouseClicked
        // TODO add your handling code here:
        String sdt = txtSDTKhachHang.getText().trim();
        if(!CheckHopLe.checkSoDienThoai(sdt)){            
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        khachHang = khachHang_BUS.findKhachHangFullBySDT(sdt);
        if(khachHang == null){            
            JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        lblTenKhachHang.setText("Tên khách hàng: " + khachHang.getTen());
        lblSDTKhachHang.setText("Số điện thoại: " + khachHang.getSdt());
        
        double mucUuDai = khachHang.getLoaiKhachHang().getMucUuDai();
        double tongThanhToan = Math.round(tongTien - tongTien * mucUuDai/100);
        int tongThanhToanInt = (int) tongThanhToan;
        
        lblMucUuDai.setText(mucUuDai + " %");
        lblTongThanhToan.setText(Price.formatPrice(tongThanhToanInt));
    }//GEN-LAST:event_btnTimKhachHangMouseClicked

    private void btnInBillTamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInBillTamMouseClicked
        JFileChooser jFileChooser= new JFileChooser("D:");
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        boolean result = false; 
       
        if (jFileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            result = donGoi_BUS.inBillTam(idBan, maNhanVien, khachHang.getId(), jFileChooser.getSelectedFile().getAbsolutePath());
        }
        
        if (!result) {
            JOptionPane.showMessageDialog(this, "In bill tạm thất bại","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInBillTamMouseClicked

    private void btnThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhToanMouseClicked
        // TODO add your handling code here:
        CreateHoaDon_DTO createHoaDon_DTO = new CreateHoaDon_DTO();
        
        createHoaDon_DTO.setMaNhanVien(maNhanVien);
        if(khachHang != null){
            createHoaDon_DTO.setIdKhachHang(khachHang.getId());
            createHoaDon_DTO.setUuDai(khachHang.getLoaiKhachHang().getMucUuDai());
        }
        
        createHoaDon_DTO.setNgayGio(Timestamp.valueOf(LocalDateTime.now()));
        createHoaDon_DTO.setTongGia(tongTien);
        
        ArrayList<CreateChiTietHoaDon_DTO> listChiTietHoaDon = new ArrayList<>();
        for(DonGoi_DTO donGoi : listDonGoi){
            int idMonAn = donGoi.getMonAn().getId();
            int soLuong = donGoi.getSoLuong();
            int gia = donGoi.getMonAn().getGiaKhuyenMai() > 0 ? 
                    donGoi.getMonAn().getGiaKhuyenMai() :
                    donGoi.getMonAn().getGia();
            
            CreateChiTietHoaDon_DTO cthd = new CreateChiTietHoaDon_DTO(idMonAn, soLuong, gia);
            listChiTietHoaDon.add(cthd);
        }
        createHoaDon_DTO.setListMonAn(listChiTietHoaDon);
        
        int idHoaDon = hoaDon_BUS.createHoaDon(createHoaDon_DTO);
        if(idHoaDon > 0){
            donGoi_BUS.deleteDonGoi(idBan);
            
            boolean result = khachHang_BUS.capNhatSauThanhToan(idHoaDon);
            if(!result)
                JOptionPane.showMessageDialog(this, "Cập nhật điểm khách hàng thất bại","Error", JOptionPane.ERROR_MESSAGE);                
            
            JFileChooser jFileChooser= new JFileChooser("D:");
            jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            boolean resultInBill = false; 

            if (jFileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                resultInBill = hoaDon_BUS.inBill(idHoaDon, jFileChooser.getSelectedFile().getAbsolutePath());
            }  
            ban_BUS.changeTinhTrangBan(idBan, TinhTrangBanConstraints.DANG_CHUAN_BI);
            this.dispose();
        }            
        else{
            JOptionPane.showMessageDialog(this, "Thanh toán thất bại","Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThanhToanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhToan_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhToan_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhToan_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhToan_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ThanhToan_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInBillTam;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnTimKhachHang;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMucUuDai;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblSDTKhachHang;
    private javax.swing.JLabel lblTenKhachHang;
    private javax.swing.JLabel lblTitleBan;
    private javax.swing.JLabel lblTongThanhToan;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JTable tblDonGoi;
    private javax.swing.JTextField txtSDTKhachHang;
    // End of variables declaration//GEN-END:variables
}
