/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author tuant
 */
public class TrangChu_GUI extends javax.swing.JFrame {
    private QuanLyPhucVu_GUI quanLyPhucVu_GUI;
    private QuanLyMonAn_GUI quanLyMonAn_GUI;
    private QuanLyLoaiBanVaBan_GUI quanLyLoaiBanVaBan_GUI;
    private QuanLyHoaDon_GUI hoaDon_GUI;
    private QuanLyNhanVien_GUI quanLyNhanVien_GUI;
    private QuanLyKhachHang_GUI quanLyKhachHang_GUI;
    private BaoCaoThongKe_GUI baoCaoThongKe_GUI;
    
    /**
     * Creates new form TrangChu_GUI
     */
    public TrangChu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnQuanLyBan = new javax.swing.JButton();
        btnQuanLyMonAn = new javax.swing.JButton();
        btnQuanLyHoaDon = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btnBaoCaoThongKe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ");
        setMinimumSize(new java.awt.Dimension(900, 520));
        setPreferredSize(new java.awt.Dimension(900, 520));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 103));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Trang chủ");
        jPanel3.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 103));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Huỳnh Tuấn Thanh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanel4.add(jLabel2, gridBagConstraints);

        jButton2.setText("Đăng xuất");
        jButton2.setFocusable(false);
        jButton2.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel4.add(jButton2, gridBagConstraints);

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setPreferredSize(new java.awt.Dimension(350, 103));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\QuanLyNhaHang\\Icon\\room_service_FILL0_wght400_GRAD0_opsz48.png")); // NOI18N
        jButton1.setText("<html> <p style =\"margin-top:60px;\"> Quản lý phục vụ</p> </html>");
        jButton1.setActionCommand("<html> <p style =\"margin-top:40px;\"> Quản lý phục vụ</p> </html>");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(10);
        jButton1.setMinimumSize(new java.awt.Dimension(200, 130));
        jButton1.setPreferredSize(new java.awt.Dimension(200, 130));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jButton1, gridBagConstraints);

        btnQuanLyBan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyBan.setIcon(new javax.swing.ImageIcon("D:\\QuanLyNhaHang\\Icon\\table_bar_FILL0_wght400_GRAD0_opsz48.png")); // NOI18N
        btnQuanLyBan.setText("<html>\n<p style =\"margin-top:60px;\">Quản lý bàn </p>\n</html>");
        btnQuanLyBan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLyBan.setMinimumSize(new java.awt.Dimension(200, 130));
        btnQuanLyBan.setPreferredSize(new java.awt.Dimension(200, 130));
        btnQuanLyBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyBanMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(btnQuanLyBan, gridBagConstraints);

        btnQuanLyMonAn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyMonAn.setIcon(new javax.swing.ImageIcon("D:\\QuanLyNhaHang\\Icon\\restaurant_menu_FILL0_wght400_GRAD0_opsz48.png")); // NOI18N
        btnQuanLyMonAn.setText("<html>\n<p style =\"margin-top:60px;\">Quản lý món ăn </p>\n</html>");
        btnQuanLyMonAn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLyMonAn.setMinimumSize(new java.awt.Dimension(200, 130));
        btnQuanLyMonAn.setPreferredSize(new java.awt.Dimension(200, 130));
        btnQuanLyMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyMonAnMouseClicked(evt);
            }
        });
        btnQuanLyMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyMonAnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(btnQuanLyMonAn, gridBagConstraints);

        btnQuanLyHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyHoaDon.setIcon(new javax.swing.ImageIcon("D:\\QuanLyNhaHang\\Icon\\receipt_long_FILL0_wght400_GRAD0_opsz48.png")); // NOI18N
        btnQuanLyHoaDon.setText("<html>\n<p style =\"margin-top:60px;\"> Quản lý hóa đơn</p>\n</html>");
        btnQuanLyHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLyHoaDon.setMinimumSize(new java.awt.Dimension(200, 130));
        btnQuanLyHoaDon.setPreferredSize(new java.awt.Dimension(200, 130));
        btnQuanLyHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyHoaDonMouseClicked(evt);
            }
        });
        jPanel2.add(btnQuanLyHoaDon, new java.awt.GridBagConstraints());

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("D:\\QuanLyNhaHang\\Icon\\person_FILL0_wght400_GRAD0_opsz48.png")); // NOI18N
        jButton6.setText("<html>\n<p style =\"margin-top:60px;\">Quản lý nhân viên</p>\n</html>");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setMinimumSize(new java.awt.Dimension(200, 130));
        jButton6.setPreferredSize(new java.awt.Dimension(200, 130));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jButton6, gridBagConstraints);

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon("D:\\QuanLyNhaHang\\Icon\\groups_FILL0_wght400_GRAD0_opsz48.png")); // NOI18N
        jButton7.setText("<html>\n<p style =\"margin-top:60px;\">Quản lý khách hàng</p>\n</html>");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setMinimumSize(new java.awt.Dimension(200, 130));
        jButton7.setPreferredSize(new java.awt.Dimension(200, 130));
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jButton7, gridBagConstraints);

        btnBaoCaoThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBaoCaoThongKe.setIcon(new javax.swing.ImageIcon("D:\\QuanLyNhaHang\\Icon\\monitoring_FILL0_wght400_GRAD200_opsz48.png")); // NOI18N
        btnBaoCaoThongKe.setText("<html>\n<p style =\"margin-top:60px;\"> Báo cáo & Thống kê</p>\n</html>");
        btnBaoCaoThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBaoCaoThongKe.setMinimumSize(new java.awt.Dimension(200, 130));
        btnBaoCaoThongKe.setPreferredSize(new java.awt.Dimension(200, 130));
        btnBaoCaoThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBaoCaoThongKeMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(btnBaoCaoThongKe, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanLyMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyMonAnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyMonAnActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(quanLyPhucVu_GUI == null || !quanLyPhucVu_GUI.isDisplayable()){
            quanLyPhucVu_GUI = new QuanLyPhucVu_GUI();
            quanLyPhucVu_GUI.setVisible(true);
        } else {
            quanLyPhucVu_GUI.setState(JFrame.NORMAL);
            quanLyPhucVu_GUI.toFront();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnQuanLyMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyMonAnMouseClicked
        // TODO add your handling code here:
        if(quanLyMonAn_GUI == null || !quanLyMonAn_GUI.isDisplayable()){
            quanLyMonAn_GUI = new QuanLyMonAn_GUI();
            quanLyMonAn_GUI.setVisible(true);
        } else {
            quanLyMonAn_GUI.setState(JFrame.NORMAL);
            quanLyMonAn_GUI.toFront();
        }
    }//GEN-LAST:event_btnQuanLyMonAnMouseClicked

    private void btnQuanLyBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyBanMouseClicked
        // TODO add your handling code here:
        if(quanLyLoaiBanVaBan_GUI == null || !quanLyLoaiBanVaBan_GUI.isDisplayable()){
            quanLyLoaiBanVaBan_GUI = new QuanLyLoaiBanVaBan_GUI();
            quanLyLoaiBanVaBan_GUI.setVisible(true);
        } else {
            quanLyLoaiBanVaBan_GUI.setState(JFrame.NORMAL);
            quanLyLoaiBanVaBan_GUI.toFront();
        }
    }//GEN-LAST:event_btnQuanLyBanMouseClicked

    private void btnQuanLyHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyHoaDonMouseClicked
        // TODO add your handling code here:
        if(hoaDon_GUI == null || !hoaDon_GUI.isDisplayable()){
            hoaDon_GUI = new QuanLyHoaDon_GUI();
            hoaDon_GUI.setVisible(true);
        } else {
            hoaDon_GUI.setState(JFrame.NORMAL);
            hoaDon_GUI.toFront();
        }
    }//GEN-LAST:event_btnQuanLyHoaDonMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        if(quanLyNhanVien_GUI == null || !quanLyNhanVien_GUI.isDisplayable()){
            quanLyNhanVien_GUI = new QuanLyNhanVien_GUI();
            quanLyNhanVien_GUI.setVisible(true);
        } else {
            quanLyNhanVien_GUI.setState(JFrame.NORMAL);
            quanLyNhanVien_GUI.toFront();
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        if(quanLyKhachHang_GUI == null || !quanLyKhachHang_GUI.isDisplayable()){
            quanLyKhachHang_GUI = new QuanLyKhachHang_GUI();
            quanLyKhachHang_GUI.setVisible(true);
        } else {
            quanLyKhachHang_GUI.setState(JFrame.NORMAL);
            quanLyKhachHang_GUI.toFront();
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void btnBaoCaoThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBaoCaoThongKeMouseClicked
        // TODO add your handling code here:
        if(baoCaoThongKe_GUI == null || !baoCaoThongKe_GUI.isDisplayable()){
            baoCaoThongKe_GUI = new BaoCaoThongKe_GUI();
            baoCaoThongKe_GUI.setVisible(true);
        } else {
            baoCaoThongKe_GUI.setState(JFrame.NORMAL);
            baoCaoThongKe_GUI.toFront();
        }
    }//GEN-LAST:event_btnBaoCaoThongKeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaoCaoThongKe;
    private javax.swing.JButton btnQuanLyBan;
    private javax.swing.JButton btnQuanLyHoaDon;
    private javax.swing.JButton btnQuanLyMonAn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
